{
  "openapi": "3.0.3",
  "info": {
    "title": "Cryptlex Web API",
    "description": "The Cryptlex Web API provides programmatic access to our services and adheres to the RESTful design principles. We strive for clear communication and ease of use for both experienced and novice developers.\n\nThe key features of the Web API are:\n1. All requests must be made over HTTPS for secure communication.\n2. All URLs are resource-oriented to help with navigating the API in a predictable manner.\n3. Responses consistently use JSON format, even for error messages.\n4. St[...]",
    "contact": {
      "email": "support@cryptlex.com"
    },
    "version": "v3",
    "x-jentic-source-url": "https://api.cryptlex.com/v3/docs"
  },
  "servers": [
    {
      "url": "https://api.cryptlex.com"
    },
    {
      "url": "https://api.eu.cryptlex.com",
      "description": "The API URL if your account is registered in the EU region."
    }
  ],
  "paths": {
    "/v3/accounts/{id}": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Retrieve an account",
        "description": "Retrieves the details of an existing account.",
        "operationId": "GetAccount",
        "security": [
          {
            "JWT": [
              "account:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Accounts"
        ],
        "summary": "Update an account",
        "description": "Updates the specified account by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateAccount",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/custom-domains": {
      "patch": {
        "tags": [
          "Accounts"
        ],
        "summary": "Update account custom domains",
        "description": "Updates the custom domains associated with the account.",
        "operationId": "UpdateCustomDomainsAccount",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/status": {
      "put": {
        "tags": [
          "Accounts"
        ],
        "summary": "Update account status",
        "description": "Updates the account status.",
        "operationId": "UpdateStatusAccount",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/subscription-status": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Get subscription status",
        "description": "Gets status, next payment date and past due grace period of subscription associated with the account",
        "operationId": "GetSubscriptionStatusAccount",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/activation-logs": {
      "get": {
        "tags": [
          "ActivationLogs"
        ],
        "summary": "List all activation logs",
        "description": "Returns a list of activation logs. The activation logs are returned sorted by creation date in ascending order.",
        "operationId": "GetAllActivationLogs",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      }
    },
    "/v3/activation-logs/{id}": {
      "get": {
        "tags": [
          "ActivationLogs"
        ],
        "summary": "Retrieve an activation log",
        "description": "Retrieves the details of an existing activation log.",
        "operationId": "GetActivationLog",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      }
    },
    "/v3/activation-logs/export": {
      "get": {
        "tags": [
          "ActivationLogs"
        ],
        "summary": "Export activation logs",
        "description": "Exports activation logs in the csv format.",
        "operationId": "ExportActivationLogs",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      }
    },
    "/v3/activations": {
      "get": {
        "tags": [
          "Activations"
        ],
        "summary": "List all activations",
        "description": "Returns a list of activations. The activations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllActivations",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Activations"
        ],
        "summary": "Create an activation",
        "description": "Creates a new activation.",
        "operationId": "CreateActivation",
        "security": [
          {}
        ]
      },
      "delete": {
        "tags": [
          "Activations"
        ],
        "summary": "Bulk delete activations",
        "description": "Bulk deletes activations for a particular license. It cannot be undone.",
        "operationId": "BulkDeleteActivation",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/activations/{id}": {
      "get": {
        "tags": [
          "Activations"
        ],
        "summary": "Retrieve an activation",
        "description": "Retrieves the details of an existing activation.",
        "operationId": "GetActivation",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Activations"
        ],
        "summary": "Update an activation",
        "description": "Updates the specified activation by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateActivation",
        "security": [
          {}
        ]
      },
      "delete": {
        "tags": [
          "Activations"
        ],
        "summary": "Delete an activation",
        "description": "Permanently deletes an activation. It cannot be undone.",
        "operationId": "DeleteActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/activations/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "Activations"
        ],
        "summary": "Get all feature entitlements for an activation",
        "description": "Get all feature entitlements for an activation.",
        "operationId": "GetAllEntitlementsActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/activations/offline-activate": {
      "post": {
        "tags": [
          "Activations"
        ],
        "summary": "Create an offline activation",
        "description": "Creates a new offline activation.",
        "operationId": "CreateOfflineActivation",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/activations/{id}/deactivate": {
      "post": {
        "tags": [
          "Activations"
        ],
        "summary": "Delete an activation",
        "description": "Permanently deletes an activation. It cannot be undone.",
        "operationId": "DeactivateActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/activations/offline-deactivate": {
      "post": {
        "tags": [
          "Activations"
        ],
        "summary": "Delete an activation offline",
        "description": "Permanently deletes an activation using offline deactivation request. It cannot be undone.",
        "operationId": "DeactivateOfflineActivation",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/activations/meter-attributes/{id}": {
      "post": {
        "tags": [
          "Activations"
        ],
        "summary": "Increment an activation meter attribute",
        "description": "Increments the activation meter attribute uses.",
        "operationId": "IncrementMeterAttributeActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/activations/export": {
      "get": {
        "tags": [
          "Activations"
        ],
        "summary": "Export activations",
        "description": "Exports activations in the csv format.",
        "operationId": "ExportActivations",
        "security": [
          {
            "JWT": [
              "activation:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/stats": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve account stats",
        "description": "Retrieves the account stats.",
        "operationId": "GetStatsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/licenses": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve licenses' stats",
        "description": "Retrieves the licenses' stats.",
        "operationId": "GetLicenseStatsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by time",
        "description": "Retrieve activations as time series data.",
        "operationId": "GetActivationsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations/os": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by OS",
        "description": "Retrieve activations by OS.",
        "operationId": "GetActivationsByOsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations/os-version": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by OS version",
        "description": "Retrieve activations by OS version.",
        "operationId": "GetActivationsByOsVersionAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations/geo-location": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by geo-location",
        "description": "Retrieve activations by geo-location.",
        "operationId": "GetActivationsByCountryAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations/release-version": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by release version",
        "description": "Retrieve activations by release version.",
        "operationId": "GetActivationsByReleaseVersionAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/activations/vm-name": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve activations by virtual machines",
        "description": "Retrieve activations by virtual machines.",
        "operationId": "GetActivationsByVmAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/trial-activations": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve trial activations by time",
        "description": "Retrieve trial activations as time series data.",
        "operationId": "GetTrialActivationsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/trial-activations/os": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve trial activations by OS",
        "description": "Retrieve trial activations by OS.",
        "operationId": "GetTrialActivationsByOsAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/trial-activations/os-version": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve trial activations by OS version",
        "description": "Retrieve trial activations by OS version.",
        "operationId": "GetTrialActivationsByOsVersionAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/trial-activations/geo-location": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve trial activations by geo-location",
        "description": "Retrieve trial activations by geo-location.",
        "operationId": "GetTrialActivationsByCountryAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/analytics/trial-activations/vm-name": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Retrieve trial activations by virtual machines",
        "description": "Retrieve trial activations by virtual machines.",
        "operationId": "GetTrialActivationsByVmAnalytics",
        "security": [
          {
            "JWT": [
              "analytics:read"
            ]
          }
        ]
      }
    },
    "/v3/accounts/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Log into the account",
        "description": "Returns an access token and the refresh token.",
        "operationId": "LoginAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/login-google": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Log into the account using Google",
        "description": "Returns an access token and the refresh token.",
        "operationId": "GoogleLoginAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/login-refresh-token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Log into the account using refresh token",
        "description": "Returns an access token and the refresh token.",
        "operationId": "RefreshTokenLoginAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/login/saml/verify": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Check whether SSO is enabled",
        "description": "Checks whether SSO is enabled for the account.",
        "operationId": "VerifySamlConfigurationAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/login/saml/{accountAlias}": {
      "get": {
        "tags": [
          "Authentication"
        ],
        "summary": "Initiate SAML SSO login",
        "description": "Redirects to the identity provider's SSO login page.",
        "operationId": "InitiateSingleSignOnAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/login/saml/{accountAlias}/acs": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "SAML assertion consumer service",
        "description": "Redirects to the service provider's return URL (relay state).",
        "operationId": "AssertionConsumerServiceAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/reset-password-request": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Send reset password email",
        "description": "Sends the reset password email.",
        "operationId": "SendPasswordResetEmailAuthentication",
        "security": [
          {}
        ]
      }
    },
    "/v3/accounts/logout": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Logout",
        "description": "Logs out the user.",
        "operationId": "LogoutAuthentication",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/automated-email-event-logs": {
      "get": {
        "tags": [
          "AutomatedEmailEventLogs"
        ],
        "summary": "List all automated email event logs",
        "description": "Returns a list of automated email event logs. The automated email event logs are returned sorted by creation date in ascending order.",
        "operationId": "GetAllAutomatedEmailEventLogs",
        "security": [
          {
            "JWT": [
              "automatedEmailEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/automated-email-event-logs/{id}": {
      "get": {
        "tags": [
          "AutomatedEmailEventLogs"
        ],
        "summary": "Retrieve an automated email event log",
        "description": "Retrieves the details of an existing automated email event log.",
        "operationId": "GetAutomatedEmailEventLog",
        "security": [
          {
            "JWT": [
              "automatedEmailEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/automated-email-event-logs/{id}/resend": {
      "post": {
        "tags": [
          "AutomatedEmailEventLogs"
        ],
        "summary": "Resend the automated email mail",
        "description": "Resends the automated email mail.",
        "operationId": "ResendAutomatedEmailEventLog",
        "security": [
          {
            "JWT": [
              "automatedEmailEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/automated-emails": {
      "get": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "List all automated emails",
        "description": "Returns a list of automated emails. The automated emails are returned sorted by creation date in ascending order.",
        "operationId": "GetAllAutomatedEmails",
        "security": [
          {
            "JWT": [
              "automatedEmail:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "Create an automated email",
        "description": "Creates a new automated email.",
        "operationId": "CreateAutomatedEmail",
        "security": [
          {
            "JWT": [
              "automatedEmail:write"
            ]
          }
        ]
      }
    },
    "/v3/automated-emails/{id}": {
      "get": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "Retrieve an automated email",
        "description": "Retrieves the details of an existing automated email.",
        "operationId": "GetAutomatedEmail",
        "security": [
          {
            "JWT": [
              "automatedEmail:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "Update an automated email",
        "description": "Updates the specified automated email by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateAutomatedEmail",
        "security": [
          {
            "JWT": [
              "automatedEmail:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "Delete an automated email",
        "description": "Permanently deletes an automated email. It cannot be undone.",
        "operationId": "DeleteAutomatedEmail",
        "security": [
          {
            "JWT": [
              "automatedEmail:write"
            ]
          }
        ]
      }
    },
    "/v3/automated-emails/events": {
      "get": {
        "tags": [
          "AutomatedEmails"
        ],
        "summary": "List all events",
        "description": "Returns a list of events based on which automated emails can be triggered.",
        "operationId": "GetEventTypesAutomatedEmail",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/billing/addresses": {
      "get": {
        "tags": [
          "BillingAddresses"
        ],
        "summary": "List all billing addresses",
        "description": "Returns a list of billing addresses. The billing addresses are returned sorted by creation date in ascending order.",
        "operationId": "GetAllBillingAddresses",
        "security": [
          {
            "JWT": [
              "paymentMethod:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "BillingAddresses"
        ],
        "summary": "Create a billing address",
        "description": "Creates a new billing address.",
        "operationId": "CreateBillingAddress",
        "security": [
          {
            "JWT": [
              "paymentMethod:write"
            ]
          }
        ]
      }
    },
    "/v3/billing/addresses/{id}": {
      "patch": {
        "tags": [
          "BillingAddresses"
        ],
        "summary": "Update a billing address",
        "description": "Update the billing address.",
        "operationId": "UpdateBillingAddress",
        "security": [
          {
            "JWT": [
              "paymentMethod:write"
            ]
          }
        ]
      }
    },
    "/v3/billing/payment-methods/cards": {
      "get": {
        "tags": [
          "CreditCards"
        ],
        "summary": "List all credit cards",
        "description": "Returns a list of credit cards. The credit cards are returned sorted by creation date in ascending order.",
        "operationId": "GetAllCreditCards",
        "security": [
          {
            "JWT": [
              "paymentMethod:read"
            ]
          }
        ]
      }
    },
    "/v3/entitlement-sets": {
      "get": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "List all entitlement sets",
        "description": "Returns a list of entitlement sets. The entitlement sets are returned sorted by creation date in ascending order.",
        "operationId": "GetAllEntitlementSets",
        "security": [
          {
            "JWT": [
              "entitlementSet:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Create an entitlement set",
        "description": "Creates a new entitlement set.",
        "operationId": "CreateEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      }
    },
    "/v3/entitlement-sets/{id}": {
      "get": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Retrieve an entitlement set",
        "description": "Retrieves the details of an existing entitlement set.",
        "operationId": "GetEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Update an entitlement set",
        "description": "Updates the specified entitlement set by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Delete an entitlement set",
        "description": "Permanently deletes an entitlement set. It cannot be undone.",
        "operationId": "DeleteEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      }
    },
    "/v3/entitlement-sets/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Get all feature entitlements belonging to an entitlement set",
        "description": "Retrieves the details of an existing entitlement set.",
        "operationId": "GetAllFeatureEntitlementsEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Add a feature entitlement to an entitlement set",
        "description": "Creates a new entitlement set.",
        "operationId": "AddEntitlementEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      }
    },
    "/v3/entitlement-sets/{id}/feature-entitlements/{entitlementId}": {
      "patch": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Update a feature entitlement belonging to an entitlement set",
        "description": "Updates the specified entitlement set by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateEntitlementEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "EntitlementSets"
        ],
        "summary": "Remove a feature entitlement from an entitlement set.",
        "description": "Permanently deletes an entitlement set. It cannot be undone.",
        "operationId": "RemoveEntitlementEntitlementSet",
        "security": [
          {
            "JWT": [
              "entitlementSet:write"
            ]
          }
        ]
      }
    },
    "/v3/event-logs": {
      "get": {
        "tags": [
          "EventLogs"
        ],
        "summary": "List all event logs",
        "description": "Returns a list of event logs. The event logs are returned sorted by creation date in ascending order.",
        "operationId": "GetAllEventLogs",
        "security": [
          {
            "JWT": [
              "eventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/event-logs/export": {
      "get": {
        "tags": [
          "EventLogs"
        ],
        "summary": "Export event logs",
        "description": "Exports event logs in the csv format.",
        "operationId": "ExportEventLogs",
        "security": [
          {
            "JWT": [
              "eventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/event-logs/{id}": {
      "get": {
        "tags": [
          "EventLogs"
        ],
        "summary": "Retrieve an event log",
        "description": "Retrieves the details of an existing event log.",
        "operationId": "GetEventLog",
        "security": [
          {
            "JWT": [
              "eventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/event-logs/resources": {
      "get": {
        "tags": [
          "EventLogs"
        ],
        "summary": "List all resources",
        "description": "Returns a list of resources that are logged in the event logs.",
        "operationId": "GetResourcesEventLog",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/feature-flags": {
      "get": {
        "tags": [
          "FeatureFlags"
        ],
        "summary": "List all feature flags",
        "description": "Returns a list of feature flags. The feature flags are returned sorted by creation date in ascending order.",
        "operationId": "GetAllFeatureFlags",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "featureFlag:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "FeatureFlags"
        ],
        "summary": "Create a feature flag",
        "description": "Creates a new feature flag.",
        "operationId": "CreateFeatureFlag",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "featureFlag:write"
            ]
          }
        ]
      }
    },
    "/v3/feature-flags/{id}": {
      "get": {
        "tags": [
          "FeatureFlags"
        ],
        "summary": "Retrieve a feature flag",
        "description": "Retrieves the details of an existing feature flag.",
        "operationId": "GetFeatureFlag",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "featureFlag:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "FeatureFlags"
        ],
        "summary": "Update a feature flag",
        "description": "Updates the specified feature flag by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateFeatureFlag",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "featureFlag:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "FeatureFlags"
        ],
        "summary": "Delete a feature flag",
        "description": "Permanently deletes a feature flag. It cannot be undone.",
        "operationId": "DeleteFeatureFlag",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "featureFlag:write"
            ]
          }
        ]
      }
    },
    "/v3/features": {
      "get": {
        "tags": [
          "Features"
        ],
        "summary": "List all features",
        "description": "Returns a list of features. The features are returned sorted by creation date in ascending order.",
        "operationId": "GetAllFeatures",
        "security": [
          {
            "JWT": [
              "feature:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Features"
        ],
        "summary": "Create a feature",
        "description": "Creates a new feature.",
        "operationId": "CreateFeature",
        "security": [
          {
            "JWT": [
              "feature:write"
            ]
          }
        ]
      }
    },
    "/v3/features/{id}": {
      "get": {
        "tags": [
          "Features"
        ],
        "summary": "Retrieve a feature",
        "description": "Retrieves the details of an existing feature.",
        "operationId": "GetFeature",
        "security": [
          {
            "JWT": [
              "feature:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Features"
        ],
        "summary": "Update a feature",
        "description": "Updates the specified feature by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateFeature",
        "security": [
          {
            "JWT": [
              "feature:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Features"
        ],
        "summary": "Delete a feature",
        "description": "Permanently deletes a feature. It cannot be undone.",
        "operationId": "DeleteFeature",
        "security": [
          {
            "JWT": [
              "feature:write"
            ]
          }
        ]
      }
    },
    "/v3/billing/invoices": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "List all invoices",
        "description": "Returns a list of invoices. The invoices are returned sorted by creation date in ascending order.",
        "operationId": "GetAllInvoices",
        "security": [
          {
            "JWT": [
              "invoice:read"
            ]
          }
        ]
      }
    },
    "/v3/billing/invoices/{id}/pdf": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "Retrieve an invoice",
        "description": "Retrieves the details of an existing invoice.",
        "operationId": "GetInvoice",
        "security": [
          {
            "JWT": [
              "invoice:read"
            ]
          }
        ]
      }
    },
    "/v3/licenses": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "List all licenses",
        "description": "Returns a list of licenses. The licenses are returned sorted by creation date in ascending order.",
        "operationId": "GetAllLicenses",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Create a license",
        "description": "Creates a new license.",
        "operationId": "CreateLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "Retrieve a license",
        "description": "Retrieves the details of an existing license.",
        "operationId": "GetLicense",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Licenses"
        ],
        "summary": "Update a license",
        "description": "Updates the specified license by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Licenses"
        ],
        "summary": "Delete a license",
        "description": "Permanently deletes a license. It cannot be undone.",
        "operationId": "DeleteLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/export": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "Export all licenses",
        "description": "Exports all licenses in the csv format.",
        "operationId": "ExportLicenses",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/renew": {
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Renew license",
        "description": "Extends the license expiry by it's subscription interval.",
        "operationId": "RenewLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/subscription": {
      "patch": {
        "tags": [
          "Licenses"
        ],
        "summary": "Update license subscription parameters",
        "description": "Update the subscription parameters for a license.",
        "operationId": "UpdateSubscriptionParametersLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/expires-at": {
      "patch": {
        "tags": [
          "Licenses"
        ],
        "summary": "Update license expiration",
        "description": "Extend a license expiration, or convert a license from perpetual to subscription and vice-versa.",
        "operationId": "UpdateExpiresAtLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/extend": {
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Extend license",
        "description": "(Deprecated) Use the update license expiration endpoint instead.",
        "operationId": "ExtendLicense",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/maintenance/renew": {
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Renew license maintenance",
        "description": "Extends the license maintenance expiry by its maintenance policy's validity.",
        "operationId": "RenewMaintenanceLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/maintenance/extend": {
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Extend license maintenance",
        "description": "Extends the license maintenance expiry by extension length.",
        "operationId": "ExtendMaintenanceLicense",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/maintenance/expires-at": {
      "patch": {
        "tags": [
          "Licenses"
        ],
        "summary": "Update license maintenance expiration",
        "description": "Update license maintenance expiration.",
        "operationId": "UpdateMaintenanceExpiresAtLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/meter-attributes/{id}/reset": {
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Reset license meter attribute",
        "description": "Resets the license meter attribute total uses.",
        "operationId": "ResetMeterAttributeLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/meter-attributes/{id}": {
      "delete": {
        "tags": [
          "Licenses"
        ],
        "summary": "Delete a license meter attribute",
        "description": "Permanently deletes a license meter attribute. It cannot be undone.",
        "operationId": "DeleteMeterAttributeLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/metadata/{id}": {
      "delete": {
        "tags": [
          "Licenses"
        ],
        "summary": "Delete a license metadata field",
        "description": "Permanently deletes a license metadata field. It cannot be undone.",
        "operationId": "DeleteMetadataLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "Get all feature entitlements for a license",
        "description": "Get all feature entitlements for a license.",
        "operationId": "GetAllFeatureEntitlementsLicense",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Licenses"
        ],
        "summary": "Create a new feature entitlement for a license",
        "description": "Create a new feature entitlement for a license.",
        "operationId": "CreateLicenseEntitlementLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/{id}/feature-entitlements/{featureEntitlementId}": {
      "patch": {
        "tags": [
          "Licenses"
        ],
        "summary": "Update a feature entitlement for a license",
        "description": "Update a feature entitlement for a license.",
        "operationId": "UpdateLicenseEntitlementLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Licenses"
        ],
        "summary": "Delete a feature entitlement for a license",
        "description": "Delete a feature entitlement for a license.",
        "operationId": "DeleteLicenseEntitlementLicense",
        "security": [
          {
            "JWT": [
              "license:write"
            ]
          }
        ]
      }
    },
    "/v3/licenses/subscription-logs": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "List all subscription logs",
        "description": "Returns a list of subscription logs. The subscription logs are returned sorted by creation date in ascending order.",
        "operationId": "GetSubscriptionLogsLicense",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      }
    },
    "/v3/licenses/subscription-logs/{id}": {
      "get": {
        "tags": [
          "Licenses"
        ],
        "summary": "Retrieve a subscription log",
        "description": "Retrieve a subscription log.",
        "operationId": "GetSubscriptionLogLicense",
        "security": [
          {
            "JWT": [
              "license:read"
            ]
          }
        ]
      }
    },
    "/v3/license-templates": {
      "get": {
        "tags": [
          "LicenseTemplates"
        ],
        "summary": "List all license templates",
        "description": "Returns a list of license templates. The license templates are returned sorted by creation date in ascending order.",
        "operationId": "GetAllLicenseTemplates",
        "security": [
          {
            "JWT": [
              "licensePolicy:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "LicenseTemplates"
        ],
        "summary": "Create a license template",
        "description": "Creates a new license template.",
        "operationId": "CreateLicenseTemplate",
        "security": [
          {
            "JWT": [
              "licensePolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/license-templates/{id}": {
      "get": {
        "tags": [
          "LicenseTemplates"
        ],
        "summary": "Retrieve a license template",
        "description": "Retrieves the details of an existing license template.",
        "operationId": "GetLicenseTemplate",
        "security": [
          {
            "JWT": [
              "licensePolicy:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "LicenseTemplates"
        ],
        "summary": "Update a license template",
        "description": "Updates the specified license template by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateLicenseTemplate",
        "security": [
          {
            "JWT": [
              "licensePolicy:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "LicenseTemplates"
        ],
        "summary": "Delete a license template",
        "description": "Permanently deletes a license template. It cannot be undone.",
        "operationId": "DeleteLicenseTemplate",
        "security": [
          {
            "JWT": [
              "licensePolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/maintenance-policies": {
      "get": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "List all maintenance policies",
        "description": "Returns a list of maintenance policies. The maintenance policies are returned sorted by creation date in ascending order.",
        "operationId": "GetAllMaintenancePolicies",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "Create a maintenance policy",
        "description": "Creates a new maintenance policy.",
        "operationId": "CreateMaintenancePolicy",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/maintenance-policies/{id}": {
      "get": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "Retrieve a maintenance policy",
        "description": "Retrieves the details of an existing maintenance policy.",
        "operationId": "GetMaintenancePolicy",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "Update a maintenance policy",
        "description": "Updates the specified maintenance policy by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateMaintenancePolicy",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "Delete a maintenance policy",
        "description": "Permanently deletes a maintenance policy. It cannot be undone.",
        "operationId": "DeleteMaintenancePolicy",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/maintenance-policies/{id}/subscription": {
      "patch": {
        "tags": [
          "MaintenancePolicies"
        ],
        "summary": "Update maintenance policy subscription parameters.",
        "description": "Update the subscription parameters for a maintenance policy.",
        "operationId": "UpdateSubscriptionMaintenancePolicy",
        "security": [
          {
            "JWT": [
              "maintenancePolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/oidc-configuration": {
      "get": {
        "tags": [
          "OidcConfigurations"
        ],
        "summary": "Retrieve an oidc configuration",
        "description": "Retrieves the details of an existing oidc configuration.",
        "operationId": "GetOidcConfiguration",
        "security": [
          {
            "JWT": [
              "account:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OidcConfigurations"
        ],
        "summary": "Create an oidc configuration",
        "description": "Creates a new oidc configuration.",
        "operationId": "CreateOidcConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "OidcConfigurations"
        ],
        "summary": "Update an oidc configuration",
        "description": "Updates the specified oidc configuration by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateOidcConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "OidcConfigurations"
        ],
        "summary": "Delete an oidc configuration",
        "description": "Permanently deletes an oidc configuration. It cannot be undone.",
        "operationId": "DeleteOidcConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/activations": {
      "get": {
        "tags": [
          "OrganizationActivations"
        ],
        "summary": "List all organization activations",
        "description": "Returns a list of organization activations. The organization activations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllOrganizationActivations",
        "security": [
          {
            "JWT": [
              "organization:activation:read"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/activations/{id}": {
      "get": {
        "tags": [
          "OrganizationActivations"
        ],
        "summary": "Retrieve an organization activation",
        "description": "Retrieves the details of an existing organization activation.",
        "operationId": "GetOrganizationActivation",
        "security": [
          {
            "JWT": [
              "organization:activation:read"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/licenses": {
      "get": {
        "tags": [
          "OrganizationLicenses"
        ],
        "summary": "List all organization licenses",
        "description": "Returns a list of organization licenses. The organization licenses are returned sorted by creation date in ascending order.",
        "operationId": "GetAllOrganizationLicenses",
        "security": [
          {
            "JWT": [
              "organization:license:read"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/licenses/{id}": {
      "get": {
        "tags": [
          "OrganizationLicenses"
        ],
        "summary": "Retrieve an organization license",
        "description": "Retrieves the details of an existing organization license.",
        "operationId": "GetOrganizationLicense",
        "security": [
          {
            "JWT": [
              "organization:license:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "OrganizationLicenses"
        ],
        "summary": "Update an organization license",
        "description": "Updates the specified organization license by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateOrganizationLicense",
        "security": [
          {
            "JWT": [
              "organization:license:update"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/licenses/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "OrganizationLicenses"
        ],
        "summary": "Retrieve a license's feature entitlements",
        "description": "Retrieves the feature entitlements of a license.",
        "operationId": "GetLicenseFeatureEntitlementsOrganizationLicense",
        "security": [
          {
            "JWT": [
              "organization:license:read"
            ]
          }
        ]
      }
    },
    "/v3/organizations": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "List all organizations",
        "description": "Returns a list of organizations. The organizations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllOrganizations",
        "security": [
          {
            "JWT": [
              "organization:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Organizations"
        ],
        "summary": "Create an organization",
        "description": "Creates a new organization.",
        "operationId": "CreateOrganization",
        "security": [
          {
            "JWT": [
              "organization:write"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{id}": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "Retrieve an organization",
        "description": "Retrieves the details of an existing organization.",
        "operationId": "GetOrganization",
        "security": [
          {
            "JWT": [
              "organization:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Organizations"
        ],
        "summary": "Update an organization",
        "description": "Updates the specified organization by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateOrganization",
        "security": [
          {
            "JWT": [
              "organization:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Organizations"
        ],
        "summary": "Delete an organization",
        "description": "Permanently deletes an organization. It cannot be undone.",
        "operationId": "DeleteOrganization",
        "security": [
          {
            "JWT": [
              "organization:write"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/user-groups": {
      "get": {
        "tags": [
          "OrganizationUserGroups"
        ],
        "summary": "List all organization user groups",
        "description": "Returns a list of organization user groups. The organization user groups are returned sorted by creation date in ascending order.",
        "operationId": "GetAllOrganizationUserGroups",
        "security": [
          {
            "JWT": [
              "organization:userGroup:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrganizationUserGroups"
        ],
        "summary": "Create an organization user group",
        "description": "Creates a new organization user group.",
        "operationId": "CreateOrganizationUserGroup",
        "security": [
          {
            "JWT": [
              "organization:userGroup:create"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/user-groups/{id}": {
      "get": {
        "tags": [
          "OrganizationUserGroups"
        ],
        "summary": "Retrieve an organization user group",
        "description": "Retrieves the details of an existing organization user group.",
        "operationId": "GetOrganizationUserGroup",
        "security": [
          {
            "JWT": [
              "organization:userGroup:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "OrganizationUserGroups"
        ],
        "summary": "Update an organization user group",
        "description": "Updates the specified organization user group by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateOrganizationUserGroup",
        "security": [
          {
            "JWT": [
              "organization:userGroup:update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "OrganizationUserGroups"
        ],
        "summary": "Delete an organization user group",
        "description": "Permanently deletes an organization user group. It cannot be undone.",
        "operationId": "DeleteOrganizationUserGroup",
        "security": [
          {
            "JWT": [
              "organization:userGroup:delete"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/users": {
      "get": {
        "tags": [
          "OrganizationUsers"
        ],
        "summary": "List all organization users",
        "description": "Returns a list of organization users. The organization users are returned sorted by creation date in ascending order.",
        "operationId": "GetAllOrganizationUsers",
        "security": [
          {
            "JWT": [
              "organization:user:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrganizationUsers"
        ],
        "summary": "Create an organization user",
        "description": "Creates a new organization user.",
        "operationId": "CreateOrganizationUser",
        "security": [
          {
            "JWT": [
              "organization:user:create"
            ]
          }
        ]
      }
    },
    "/v3/organizations/{organizationId}/users/{id}": {
      "get": {
        "tags": [
          "OrganizationUsers"
        ],
        "summary": "Retrieve an organization user",
        "description": "Retrieves the details of an existing organization user.",
        "operationId": "GetOrganizationUser",
        "security": [
          {
            "JWT": [
              "organization:user:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "OrganizationUsers"
        ],
        "summary": "Update an organization user",
        "description": "Updates the specified organization user by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateOrganizationUser",
        "security": [
          {
            "JWT": [
              "organization:user:update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "OrganizationUsers"
        ],
        "summary": "Delete an organization user",
        "description": "Permanently deletes an organization user. It cannot be undone.",
        "operationId": "DeleteOrganizationUser",
        "security": [
          {
            "JWT": [
              "organization:user:delete"
            ]
          }
        ]
      }
    },
    "/v3/personal-access-tokens": {
      "get": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "List all personal access tokens",
        "description": "Returns a list of personal access tokens. The personal access tokens are returned sorted by creation date in ascending order.",
        "operationId": "GetAllPersonalAccessTokens",
        "security": [
          {
            "JWT": []
          }
        ]
      },
      "post": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "Create a personal access token",
        "description": "Creates a new personal access token.",
        "operationId": "CreatePersonalAccessToken",
        "security": [
          {
            "JWT": [
              "personalAccessToken:write"
            ]
          }
        ]
      }
    },
    "/v3/personal-access-tokens/{id}": {
      "get": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "Retrieve a personal access token",
        "description": "Retrieves the details of an existing personal access token.",
        "operationId": "GetPersonalAccessToken",
        "security": [
          {
            "JWT": []
          }
        ]
      },
      "patch": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "Update a personal access token",
        "description": "Updates the specified personal access token by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdatePersonalAccessToken",
        "security": [
          {
            "JWT": [
              "personalAccessToken:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "Delete a personal access token",
        "description": "Permanently deletes a personal access token. It cannot be undone.",
        "operationId": "DeletePersonalAccessToken",
        "security": [
          {
            "JWT": [
              "personalAccessToken:write"
            ]
          }
        ]
      }
    },
    "/v3/personal-access-tokens/{id}/rotate": {
      "post": {
        "tags": [
          "PersonalAccessTokens"
        ],
        "summary": "Create a personal access token",
        "description": "Creates a new personal access token.",
        "operationId": "RotatePersonalAccessToken",
        "security": [
          {
            "JWT": [
              "personalAccessToken:write"
            ]
          }
        ]
      }
    },
    "/v3/plans": {
      "get": {
        "tags": [
          "Plans"
        ],
        "summary": "List all plans",
        "description": "Returns a list of plans. The plans are returned sorted by creation date in ascending order.",
        "operationId": "GetAllPlans",
        "security": [
          {}
        ]
      }
    },
    "/v3/plans/{id}": {
      "get": {
        "tags": [
          "Plans"
        ],
        "summary": "Retrieve a plan",
        "description": "Retrieves the details of an existing plan.",
        "operationId": "GetPlan",
        "security": [
          {}
        ]
      }
    },
    "/v3/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "List all products",
        "description": "Returns a list of products. The products are returned sorted by creation date in ascending order.",
        "operationId": "GetAllProducts",
        "security": [
          {
            "JWT": [
              "product:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Create a product",
        "description": "Creates a new product.",
        "operationId": "CreateProduct",
        "security": [
          {
            "JWT": [
              "product:write"
            ]
          }
        ]
      }
    },
    "/v3/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Retrieve a product",
        "description": "Retrieves the details of an existing product.",
        "operationId": "GetProduct",
        "security": [
          {
            "JWT": [
              "product:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Products"
        ],
        "summary": "Update a product",
        "description": "Updates the specified product by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateProduct",
        "security": [
          {
            "JWT": [
              "product:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete a product",
        "description": "Permanently deletes a product. It cannot be undone.",
        "operationId": "DeleteProduct",
        "security": [
          {
            "JWT": [
              "product:write"
            ]
          }
        ]
      }
    },
    "/v3/products/{id}/product.dat": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Download the Product Data file",
        "description": "Retrieves the details of an existing product.",
        "operationId": "GetDataFileProduct",
        "security": [
          {
            "JWT": [
              "product:read"
            ]
          }
        ]
      }
    },
    "/v3/products/metadata/{id}": {
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete a product metadata field",
        "description": "Permanently deletes a product metadata field. It cannot be undone.",
        "operationId": "DeleteMetadataProduct",
        "security": [
          {
            "JWT": [
              "product:write"
            ]
          }
        ]
      }
    },
    "/v3/product-versions": {
      "get": {
        "tags": [
          "ProductVersions"
        ],
        "summary": "List all product versions",
        "description": "Returns a list of product versions. The product versions are returned sorted by creation date in ascending order.",
        "operationId": "GetAllProductVersions",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "productVersion:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ProductVersions"
        ],
        "summary": "Create a product version",
        "description": "Creates a new product version.",
        "operationId": "CreateProductVersion",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "productVersion:write"
            ]
          }
        ]
      }
    },
    "/v3/product-versions/{id}": {
      "get": {
        "tags": [
          "ProductVersions"
        ],
        "summary": "Retrieve a product version",
        "description": "Retrieves the details of an existing product version.",
        "operationId": "GetProductVersion",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "productVersion:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ProductVersions"
        ],
        "summary": "Update a product version",
        "description": "Updates the specified product version by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateProductVersion",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "productVersion:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ProductVersions"
        ],
        "summary": "Delete a product version",
        "description": "Permanently deletes a product version. It cannot be undone.",
        "operationId": "DeleteProductVersion",
        "deprecated": true,
        "security": [
          {
            "JWT": [
              "productVersion:write"
            ]
          }
        ]
      }
    },
    "/v3/me": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Retrieve profile",
        "description": "Retrieves the details of the currently authenticated user.",
        "operationId": "GetProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      },
      "patch": {
        "tags": [
          "Profile"
        ],
        "summary": "Update profile",
        "description": "Updates the currently authenticated user by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/licenses": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all licenses",
        "description": "Returns a list of licenses of the currently authenticated user. The licenses are returned sorted by creation date in ascending order.",
        "operationId": "GetLicensesProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/licenses/{id}": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Retrieve a license",
        "description": "Retrieves the details of an existing license.",
        "operationId": "GetLicenseProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/licenses/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Retrieve a license's feature entitlements",
        "description": "Retrieves the feature entitlements of a license.",
        "operationId": "GetLicenseFeatureEntitlementsProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/activations": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all activations",
        "description": "Returns a list of activations of the currently authenticated user. The activations are returned sorted by creation date in ascending order.",
        "operationId": "GetActivationsProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/activations/{id}": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Retrieve an activation",
        "description": "Retrieves the details of an existing activation.",
        "operationId": "GetActivationProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/releases": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all releases",
        "description": "Returns a list of published releases which can be downloaded by the currently authenticated user. The releases are returned sorted by published date, with the most recent published release appearing first.",
        "operationId": "GetReleasesProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/release-platforms": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all release platforms",
        "description": "Returns a list of release platforms. The release platforms are returned sorted by creation date in ascending order.",
        "operationId": "GetReleasePlatformsProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/release-channels": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all release channels",
        "description": "Returns a list of release channels. The release channels are returned sorted by creation date in ascending order.",
        "operationId": "GetReleaseChannelsProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/products": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "List all products",
        "description": "Returns a list of products which are associated with the currently authenticated user.",
        "operationId": "GetProductsProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/email-preferences": {
      "patch": {
        "tags": [
          "Profile"
        ],
        "summary": "Update user email preferences",
        "description": "Updates the email preferences for a user.",
        "operationId": "UpdateEmailPreferencesProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/2fa-secret": {
      "post": {
        "tags": [
          "Profile"
        ],
        "summary": "Generate the 2FA secret",
        "description": "Generates the 2FA secret for Authenticator app.",
        "operationId": "Generate2faSecretProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/me/2fa-recovery-codes": {
      "post": {
        "tags": [
          "Profile"
        ],
        "summary": "Generate the 2FA recovery codes",
        "description": "Generates the 2FA recovery codes.",
        "operationId": "Generate2faRecoveryCodesProfile",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/release-channels": {
      "get": {
        "tags": [
          "ReleaseChannels"
        ],
        "summary": "List all release channels",
        "description": "Returns a list of release channels. The release channels are returned sorted by creation date in ascending order.",
        "operationId": "GetAllReleaseChannels",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ReleaseChannels"
        ],
        "summary": "Create a release channel",
        "description": "Creates a new release channel.",
        "operationId": "CreateReleaseChannel",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/release-channels/{id}": {
      "get": {
        "tags": [
          "ReleaseChannels"
        ],
        "summary": "Retrieve a release channel",
        "description": "Retrieves the details of an existing release channel.",
        "operationId": "GetReleaseChannel",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ReleaseChannels"
        ],
        "summary": "Update a release channel",
        "description": "Updates the specified release channel by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateReleaseChannel",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ReleaseChannels"
        ],
        "summary": "Delete a release channel",
        "description": "Permanently deletes a release channel. It cannot be undone.",
        "operationId": "DeleteReleaseChannel",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/release-files": {
      "get": {
        "tags": [
          "ReleaseFiles"
        ],
        "summary": "List all release files",
        "description": "Returns a list of release files. The release files are returned sorted by creation date in ascending order.",
        "operationId": "GetAllReleaseFiles",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ReleaseFiles"
        ],
        "summary": "Create a release file",
        "description": "Creates a new release file.",
        "operationId": "CreateReleaseFile",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/release-files/{id}": {
      "get": {
        "tags": [
          "ReleaseFiles"
        ],
        "summary": "Retrieve a release file",
        "description": "Retrieves the details of an existing release file.",
        "operationId": "GetReleaseFile",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ReleaseFiles"
        ],
        "summary": "Delete a release file",
        "description": "Permanently deletes a release file. It cannot be undone.",
        "operationId": "DeleteReleaseFile",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/release-platforms": {
      "get": {
        "tags": [
          "ReleasePlatforms"
        ],
        "summary": "List all release platforms",
        "description": "Returns a list of release platforms. The release platforms are returned sorted by creation date in ascending order.",
        "operationId": "GetAllReleasePlatforms",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ReleasePlatforms"
        ],
        "summary": "Create a release platform",
        "description": "Creates a new release platform.",
        "operationId": "CreateReleasePlatform",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/release-platforms/{id}": {
      "get": {
        "tags": [
          "ReleasePlatforms"
        ],
        "summary": "Retrieve a release platform",
        "description": "Retrieves the details of an existing release platform.",
        "operationId": "GetReleasePlatform",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ReleasePlatforms"
        ],
        "summary": "Update a release platform",
        "description": "Updates the specified release platform by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateReleasePlatform",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ReleasePlatforms"
        ],
        "summary": "Delete a release platform",
        "description": "Permanently deletes a release platform. It cannot be undone.",
        "operationId": "DeleteReleasePlatform",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/releases": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "List all releases",
        "description": "Returns a list of releases. The releases are returned sorted by creation date in ascending order.",
        "operationId": "GetAllReleases",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Releases"
        ],
        "summary": "Create a release",
        "description": "Creates a new release.",
        "operationId": "CreateRelease",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/releases/{id}": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "Retrieve a release",
        "description": "Retrieves the details of an existing release.",
        "operationId": "GetRelease",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Releases"
        ],
        "summary": "Update a release",
        "description": "Updates the specified release by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateRelease",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Releases"
        ],
        "summary": "Delete a release",
        "description": "Permanently deletes a release. It cannot be undone.",
        "operationId": "DeleteRelease",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/releases/update": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "Check for an update",
        "description": "Checks whether a new release is available by comparing with the provided release version.",
        "operationId": "GetUpdateRelease",
        "security": [
          {}
        ]
      }
    },
    "/v3/releases/latest": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "Get latest release",
        "description": "Gets the latest release.",
        "operationId": "GetLatestRelease",
        "security": [
          {}
        ]
      }
    },
    "/v3/releases/{id}/allowed": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "Check if release is allowed",
        "description": "Checks whether a release is allowed depending on the maintenance policy or max allowed release version set in the license.",
        "operationId": "IsAllowedRelease",
        "security": [
          {}
        ]
      }
    },
    "/v3/releases/{id}/publish": {
      "post": {
        "tags": [
          "Releases"
        ],
        "summary": "Publish release",
        "description": "After the release is published it can't be modified. The /update and /latest endpoints will start returning the published release.",
        "operationId": "PublishRelease",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/releases/{id}/archive": {
      "post": {
        "tags": [
          "Releases"
        ],
        "summary": "Archive release",
        "description": "After a published release is archived it is not shown to end users.",
        "operationId": "ArchiveRelease",
        "security": [
          {
            "JWT": [
              "release:write"
            ]
          }
        ]
      }
    },
    "/v3/releases/storage": {
      "get": {
        "tags": [
          "Releases"
        ],
        "summary": "Get release storage space information",
        "description": "Storage space information including used and allowed space",
        "operationId": "GetStorageSpaceRelease",
        "security": [
          {
            "JWT": [
              "release:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/activations": {
      "get": {
        "tags": [
          "ResellerActivations"
        ],
        "summary": "List all reseller activations",
        "description": "Returns a list of reseller activations. The reseller activations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllResellerActivations",
        "security": [
          {
            "JWT": [
              "reseller:activation:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/activations/{id}": {
      "get": {
        "tags": [
          "ResellerActivations"
        ],
        "summary": "Retrieve a reseller activation",
        "description": "Retrieves the details of an existing reseller activation.",
        "operationId": "GetResellerActivation",
        "security": [
          {
            "JWT": [
              "reseller:activation:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/activations/export": {
      "get": {
        "tags": [
          "ResellerActivations"
        ],
        "summary": "Export reseller activations",
        "description": "Exports reseller activations in the csv format.",
        "operationId": "ExportResellerActivations",
        "security": [
          {
            "JWT": [
              "reseller:activation:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/licenses": {
      "get": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "List all reseller licenses",
        "description": "Returns a list of reseller licenses. The reseller licenses are returned sorted by creation date in ascending order.",
        "operationId": "GetAllResellerLicenses",
        "security": [
          {
            "JWT": [
              "reseller:license:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/licenses/{id}": {
      "get": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "Retrieve a reseller license",
        "description": "Retrieves the details of an existing reseller license.",
        "operationId": "GetResellerLicense",
        "security": [
          {
            "JWT": [
              "reseller:license:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "Update a reseller license",
        "description": "Updates the specified reseller license by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateResellerLicense",
        "security": [
          {
            "JWT": [
              "reseller:license:update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "Delete a reseller license",
        "description": "Permanently deletes a reseller license. It cannot be undone.",
        "operationId": "DeleteResellerLicense",
        "security": [
          {
            "JWT": [
              "reseller:license:delete"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/licenses/{id}/feature-entitlements": {
      "get": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "Retrieve a license's feature entitlements",
        "description": "Retrieves the feature entitlements of a license.",
        "operationId": "GetLicenseFeatureEntitlementsResellerLicense",
        "security": [
          {
            "JWT": [
              "reseller:license:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/licenses/export": {
      "get": {
        "tags": [
          "ResellerLicenses"
        ],
        "summary": "Export reseller licenses",
        "description": "Exports reseller licenses in the csv format.",
        "operationId": "ExportResellerLicenses",
        "security": [
          {
            "JWT": [
              "reseller:license:read"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/organizations": {
      "get": {
        "tags": [
          "ResellerOrganizations"
        ],
        "summary": "List all reseller organizations",
        "description": "Returns a list of reseller organizations. The reseller organizations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllResellerOrganizations",
        "security": [
          {
            "JWT": [
              "reseller:organization:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ResellerOrganizations"
        ],
        "summary": "Create a reseller organization",
        "description": "Creates a new reseller organization.",
        "operationId": "CreateResellerOrganization",
        "security": [
          {
            "JWT": [
              "reseller:organization:create"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/organizations/{id}": {
      "get": {
        "tags": [
          "ResellerOrganizations"
        ],
        "summary": "Retrieve a reseller organization",
        "description": "Retrieves the details of an existing reseller organization.",
        "operationId": "GetResellerOrganization",
        "security": [
          {
            "JWT": [
              "reseller:organization:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ResellerOrganizations"
        ],
        "summary": "Update a reseller organization",
        "description": "Updates the specified reseller organization by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateResellerOrganization",
        "security": [
          {
            "JWT": [
              "reseller:organization:update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ResellerOrganizations"
        ],
        "summary": "Delete a reseller organization",
        "description": "Permanently deletes a reseller organization. It cannot be undone.",
        "operationId": "DeleteResellerOrganization",
        "security": [
          {
            "JWT": [
              "reseller:organization:delete"
            ]
          }
        ]
      }
    },
    "/v3/resellers": {
      "get": {
        "tags": [
          "Resellers"
        ],
        "summary": "List all resellers",
        "description": "Returns a list of resellers. The resellers are returned sorted by creation date in ascending order.",
        "operationId": "GetAllResellers",
        "security": [
          {
            "JWT": [
              "reseller:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Resellers"
        ],
        "summary": "Create a reseller",
        "description": "Creates a new reseller.",
        "operationId": "CreateReseller",
        "security": [
          {
            "JWT": [
              "reseller:write"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{id}": {
      "get": {
        "tags": [
          "Resellers"
        ],
        "summary": "Retrieve a reseller",
        "description": "Retrieves the details of an existing reseller.",
        "operationId": "GetReseller",
        "security": [
          {
            "JWT": [
              "reseller:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Resellers"
        ],
        "summary": "Update a reseller",
        "description": "Updates the specified reseller by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateReseller",
        "security": [
          {
            "JWT": [
              "reseller:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Resellers"
        ],
        "summary": "Delete a reseller",
        "description": "Permanently deletes a reseller. It cannot be undone.",
        "operationId": "DeleteReseller",
        "security": [
          {
            "JWT": [
              "reseller:write"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/users": {
      "get": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "List all reseller users",
        "description": "Returns a list of reseller users. The reseller users are returned sorted by creation date in ascending order.",
        "operationId": "GetAllResellerUsers",
        "security": [
          {
            "JWT": [
              "reseller:user:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "Create a reseller user",
        "description": "Creates a new reseller user.",
        "operationId": "CreateResellerUser",
        "security": [
          {
            "JWT": [
              "reseller:user:create"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/users/{id}": {
      "get": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "Retrieve a reseller user",
        "description": "Retrieves the details of an existing reseller user.",
        "operationId": "GetResellerUser",
        "security": [
          {
            "JWT": [
              "reseller:user:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "Update a reseller user",
        "description": "Updates the specified reseller user by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateResellerUser",
        "security": [
          {
            "JWT": [
              "reseller:user:update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "Delete a reseller user",
        "description": "Permanently deletes a reseller user. It cannot be undone.",
        "operationId": "DeleteResellerUser",
        "security": [
          {
            "JWT": [
              "reseller:user:delete"
            ]
          }
        ]
      }
    },
    "/v3/resellers/{resellerId}/users/export": {
      "get": {
        "tags": [
          "ResellerUsers"
        ],
        "summary": "Export reseller users",
        "description": "Exports reseller users in the csv format.",
        "operationId": "ExportResellerUsers",
        "security": [
          {
            "JWT": [
              "reseller:user:read"
            ]
          }
        ]
      }
    },
    "/v3/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List all roles",
        "description": "Returns a list of roles. The roles are returned sorted by creation date in ascending order.",
        "operationId": "GetAllRoles",
        "security": [
          {
            "JWT": [
              "role:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Create a role",
        "description": "Creates a new role.",
        "operationId": "CreateRole",
        "security": [
          {
            "JWT": [
              "role:write"
            ]
          }
        ]
      }
    },
    "/v3/roles/claims": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List all role claims",
        "description": "Returns the list of all the role claims (permissions).",
        "operationId": "GetClaimsRole",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/roles/{id}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Retrieve a role",
        "description": "Retrieves the details of an existing role.",
        "operationId": "GetRole",
        "security": [
          {
            "JWT": [
              "role:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Roles"
        ],
        "summary": "Update a role",
        "description": "Updates the specified role by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateRole",
        "security": [
          {
            "JWT": [
              "role:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Delete a role",
        "description": "Permanently deletes a role. It cannot be undone.",
        "operationId": "DeleteRole",
        "security": [
          {
            "JWT": [
              "role:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/saml-configuration": {
      "get": {
        "tags": [
          "SamlConfigurations"
        ],
        "summary": "Retrieve a saml configuration",
        "description": "Retrieves the details of an existing saml configuration.",
        "operationId": "GetSamlConfiguration",
        "security": [
          {
            "JWT": [
              "account:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "SamlConfigurations"
        ],
        "summary": "Create a saml configuration",
        "description": "Creates a new saml configuration.",
        "operationId": "CreateSamlConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "SamlConfigurations"
        ],
        "summary": "Update a saml configuration",
        "description": "Updates the specified saml configuration by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateSamlConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "SamlConfigurations"
        ],
        "summary": "Delete a saml configuration",
        "description": "Permanently deletes a saml configuration. It cannot be undone.",
        "operationId": "DeleteSamlConfiguration",
        "security": [
          {
            "JWT": [
              "account:write"
            ]
          }
        ]
      }
    },
    "/v3/accounts/{id}/saml-configuration/certificate.pem": {
      "get": {
        "tags": [
          "SamlConfigurations"
        ],
        "summary": "Download service provider certificate",
        "description": "Downloads the service provider certificate.",
        "operationId": "GetServiceProviderCertificateSamlConfiguration",
        "security": [
          {}
        ]
      }
    },
    "/v3/segments": {
      "get": {
        "tags": [
          "Segments"
        ],
        "summary": "List all segments",
        "description": "Returns a list of segments. The segments are returned sorted by creation date in ascending order.",
        "operationId": "GetAllSegments",
        "security": [
          {
            "JWT": [
              "segment:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Segments"
        ],
        "summary": "Create a segment",
        "description": "Creates a new segment.",
        "operationId": "CreateSegment",
        "security": [
          {
            "JWT": [
              "segment:write"
            ]
          }
        ]
      }
    },
    "/v3/segments/{id}": {
      "get": {
        "tags": [
          "Segments"
        ],
        "summary": "Retrieve a segment",
        "description": "Retrieves the details of an existing segment.",
        "operationId": "GetSegment",
        "security": [
          {
            "JWT": [
              "segment:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Segments"
        ],
        "summary": "Update a segment",
        "description": "Updates the specified segment by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateSegment",
        "security": [
          {
            "JWT": [
              "segment:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Segments"
        ],
        "summary": "Delete a segment",
        "description": "Permanently deletes a segment. It cannot be undone.",
        "operationId": "DeleteSegment",
        "security": [
          {
            "JWT": [
              "segment:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains": {
      "get": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "List all sending domains",
        "description": "Returns a list of sending domains. The sending domains are returned sorted by creation date in ascending order.",
        "operationId": "GetAllSendingDomains",
        "security": [
          {
            "JWT": [
              "sendingDomain:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Create a sending domain",
        "description": "Creates a new sending domain.",
        "operationId": "CreateSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains/{id}": {
      "get": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Retrieve a sending domain",
        "description": "Retrieves the details of an existing sending domain.",
        "operationId": "GetSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Delete a sending domain",
        "description": "Permanently deletes a sending domain. It cannot be undone.",
        "operationId": "DeleteSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains/{id}/verify": {
      "post": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Create a sending domain",
        "description": "Creates a new sending domain.",
        "operationId": "VerifySendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains/{id}/allowed-from-emails": {
      "put": {
        "tags": [
          "SendingDomains"
        ],
        "operationId": "AddAllowedFromEmailsSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains/{id}/allowed-from-emails/send-verification": {
      "post": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Create a sending domain",
        "description": "Creates a new sending domain.",
        "operationId": "SendVerificationSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/sending-domains/{id}/allowed-from-emails/verify": {
      "post": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Create a sending domain",
        "description": "Creates a new sending domain.",
        "operationId": "VerifyEmailSendingDomain",
        "security": [
          {}
        ]
      }
    },
    "/v3/sending-domains/{id}/allowed-from-emails/{email}": {
      "delete": {
        "tags": [
          "SendingDomains"
        ],
        "summary": "Delete a sending domain",
        "description": "Permanently deletes a sending domain. It cannot be undone.",
        "operationId": "DeleteAllowedFromEmailSendingDomain",
        "security": [
          {
            "JWT": [
              "sendingDomain:write"
            ]
          }
        ]
      }
    },
    "/v3/tags": {
      "get": {
        "tags": [
          "Tags"
        ],
        "summary": "List all tags",
        "description": "Returns a list of tags. The tags are returned sorted by creation date in ascending order.",
        "operationId": "GetAllTags",
        "security": [
          {
            "JWT": [
              "tag:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Tags"
        ],
        "summary": "Create a tag",
        "description": "Creates a new tag.",
        "operationId": "CreateTag",
        "security": [
          {
            "JWT": [
              "tag:write"
            ]
          }
        ]
      }
    },
    "/v3/tags/{id}": {
      "get": {
        "tags": [
          "Tags"
        ],
        "summary": "Retrieve a tag",
        "description": "Retrieves the details of an existing tag.",
        "operationId": "GetTag",
        "security": [
          {
            "JWT": [
              "tag:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Tags"
        ],
        "summary": "Update a tag",
        "description": "Updates the specified tag by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateTag",
        "security": [
          {
            "JWT": [
              "tag:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tags"
        ],
        "summary": "Delete a tag",
        "description": "Permanently deletes a tag. It cannot be undone.",
        "operationId": "DeleteTag",
        "security": [
          {
            "JWT": [
              "tag:write"
            ]
          }
        ]
      }
    },
    "/v3/trial-activations": {
      "get": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "List all trial activations",
        "description": "Returns a list of trial activations. The trial activations are returned sorted by creation date in ascending order.",
        "operationId": "GetAllTrialActivations",
        "security": [
          {
            "JWT": [
              "trialActivation:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Create a trial activation",
        "description": "Creates a new trial activation.",
        "operationId": "CreateTrialActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/trial-activations/{id}": {
      "get": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Retrieve a trial activation",
        "description": "Retrieves the details of an existing trial activation.",
        "operationId": "GetTrialActivation",
        "security": [
          {
            "JWT": [
              "trialActivation:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Update a trial activation",
        "description": "Updates the specified trial activation by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateTrialActivation",
        "security": [
          {}
        ]
      },
      "delete": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Delete a trial activation",
        "description": "Permanently deletes a trial activation. It cannot be undone.",
        "operationId": "DeleteTrialActivation",
        "security": [
          {
            "JWT": [
              "trialActivation:write"
            ]
          }
        ]
      }
    },
    "/v3/trial-activations/export": {
      "get": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Export all trial activations",
        "description": "Exports all trial activations in the csv format.",
        "operationId": "ExportTrialActivations",
        "security": [
          {
            "JWT": [
              "trialActivation:read"
            ]
          }
        ]
      }
    },
    "/v3/trial-activations/{id}/extend": {
      "post": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Extend a trial activation",
        "description": "Extends the trial expiry by extension length.",
        "operationId": "ExtendTrialActivation",
        "security": [
          {
            "JWT": [
              "trialActivation:write"
            ]
          }
        ]
      }
    },
    "/v3/trial-activations/{id}/expires-at": {
      "patch": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Update trial activation expiry date",
        "description": "Updates the trial activation expiry date.",
        "operationId": "UpdateExpiresAtTrialActivation",
        "security": [
          {
            "JWT": [
              "trialActivation:write"
            ]
          }
        ]
      }
    },
    "/v3/trial-activations/offline-activate": {
      "post": {
        "tags": [
          "TrialActivations"
        ],
        "summary": "Create an offline trial activation",
        "description": "Creates a new offline trial activation.",
        "operationId": "CreateOfflineTrialActivation",
        "security": [
          {}
        ]
      }
    },
    "/v3/trial-policies": {
      "get": {
        "tags": [
          "TrialPolicies"
        ],
        "summary": "List all trial policies",
        "description": "Returns a list of trial policies. The trial policies are returned sorted by creation date in ascending order.",
        "operationId": "GetAllTrialPolicies",
        "security": [
          {
            "JWT": [
              "trialPolicy:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "TrialPolicies"
        ],
        "summary": "Create a trial policy",
        "description": "Creates a new trial policy.",
        "operationId": "CreateTrialPolicy",
        "security": [
          {
            "JWT": [
              "trialPolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/trial-policies/{id}": {
      "get": {
        "tags": [
          "TrialPolicies"
        ],
        "summary": "Retrieve a trial policy",
        "description": "Retrieves the details of an existing trial policy.",
        "operationId": "GetTrialPolicy",
        "security": [
          {
            "JWT": [
              "trialPolicy:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "TrialPolicies"
        ],
        "summary": "Update a trial policy",
        "description": "Updates the specified trial policy by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateTrialPolicy",
        "security": [
          {
            "JWT": [
              "trialPolicy:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "TrialPolicies"
        ],
        "summary": "Delete a trial policy",
        "description": "Permanently deletes a trial policy. It cannot be undone.",
        "operationId": "DeleteTrialPolicy",
        "security": [
          {
            "JWT": [
              "trialPolicy:write"
            ]
          }
        ]
      }
    },
    "/v3/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "List all users",
        "description": "Returns a list of users. The users are returned sorted by creation date in ascending order.",
        "operationId": "GetAllUsers",
        "security": [
          {
            "JWT": [
              "user:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create a user",
        "description": "Creates a new user.",
        "operationId": "CreateUser",
        "security": [
          {
            "JWT": [
              "user:write"
            ]
          }
        ]
      }
    },
    "/v3/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Retrieve a user",
        "description": "Retrieves the details of an existing user.",
        "operationId": "GetUser",
        "security": [
          {
            "JWT": [
              "user:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "summary": "Update a user",
        "description": "Updates the specified user by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateUser",
        "security": [
          {
            "JWT": [
              "user:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete a user",
        "description": "Permanently deletes a user. It cannot be undone.",
        "operationId": "DeleteUser",
        "security": [
          {
            "JWT": [
              "user:write"
            ]
          }
        ]
      }
    },
    "/v3/users/export": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Export all users",
        "description": "Exports all users in the csv format.",
        "operationId": "ExportUsers",
        "security": [
          {
            "JWT": [
              "user:read"
            ]
          }
        ]
      }
    },
    "/v3/users/{id}/update-password": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Update password",
        "description": "Update the user's password. A user's password can only be updated when authenticated as the given user.",
        "operationId": "UpdatePasswordUser",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/v3/users/{id}/reset-password-token": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Generate reset password token",
        "description": "Generates the reset password token (url encoded) for users with 'user', 'organization-admin' and 'reseller-admin' roles. It should only be used for custom customer portals to implement password reset.",
        "operationId": "CreateResetPasswordTokenUser",
        "security": [
          {
            "JWT": [
              "user:write"
            ]
          }
        ]
      }
    },
    "/v3/users/{id}/reset-password": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Reset password",
        "description": "Update the user's password using password reset token.",
        "operationId": "ResetPasswordUser",
        "security": [
          {}
        ]
      }
    },
    "/v3/users/metadata/{id}": {
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete a user metadata field",
        "description": "Permanently deletes a user metadata field. It cannot be undone.",
        "operationId": "DeleteMetadataUser",
        "security": [
          {
            "JWT": [
              "user:write"
            ]
          }
        ]
      }
    },
    "/v3/webhook-event-logs": {
      "get": {
        "tags": [
          "WebhookEventLogs"
        ],
        "summary": "List all webhook event logs",
        "description": "Returns a list of webhook event logs. The webhook event logs are returned sorted by creation date in ascending order.",
        "operationId": "GetAllWebhookEventLogs",
        "security": [
          {
            "JWT": [
              "webhookEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/webhook-event-logs/{id}": {
      "get": {
        "tags": [
          "WebhookEventLogs"
        ],
        "summary": "Retrieve a webhook event log",
        "description": "Retrieves the details of an existing webhook event log.",
        "operationId": "GetWebhookEventLog",
        "security": [
          {
            "JWT": [
              "webhookEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/webhook-event-logs/{id}/resend": {
      "post": {
        "tags": [
          "WebhookEventLogs"
        ],
        "summary": "Resend the webhook",
        "description": "Resends the webhook.",
        "operationId": "ResendWebhookEventLog",
        "security": [
          {
            "JWT": [
              "webhookEventLog:read"
            ]
          }
        ]
      }
    },
    "/v3/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List all webhooks",
        "description": "Returns a list of webhooks. The webhooks are returned sorted by creation date in ascending order.",
        "operationId": "GetAllWebhooks",
        "security": [
          {
            "JWT": [
              "webhook:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Create a webhook",
        "description": "Creates a new webhook.",
        "operationId": "CreateWebhook",
        "security": [
          {
            "JWT": [
              "webhook:write"
            ]
          }
        ]
      }
    },
    "/v3/webhooks/{id}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Retrieve a webhook",
        "description": "Retrieves the details of an existing webhook.",
        "operationId": "GetWebhook",
        "security": [
          {
            "JWT": [
              "webhook:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Update a webhook",
        "description": "Updates the specified webhook by setting the values of the parameters passed. Any parameters not provided will be left unchanged.",
        "operationId": "UpdateWebhook",
        "security": [
          {
            "JWT": [
              "webhook:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Delete a webhook",
        "description": "Permanently deletes a webhook. It cannot be undone.",
        "operationId": "DeleteWebhook",
        "security": [
          {
            "JWT": [
              "webhook:write"
            ]
          }
        ]
      }
    },
    "/v3/webhooks/events": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List all events",
        "description": "Returns a list of all the events which can be subscribed to using webhooks.",
        "operationId": "GetEventTypesWebhook",
        "security": [
          {
            "JWT": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "JWT": {
        "type": "http",
        "description": "Utilize the Bearer token scheme with your access token included in the Authorization HTTP header.\n```Authorization: Bearer YOUR_ACCESS_TOKEN```",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "Accounts",
      "description": "Account management helps you manage your account related details. It includes API endpoints for updating account details, changing account status, changing account plan etc.",
      "x-displayName": "Accounts"
    },
    {
      "name": "ActivationLogs",
      "description": "Activation logs provide a complete history of all the license activations and deactivations.\n\nThey can be used for auditing the license usage over time.",
      "x-displayName": "Activation Logs"
    },
    {
      "name": "Activations",
      "description": "A license activation is said to occur when your customer uses a license key to activate the license in your application on his/her machine.\n\nBy default all activations are node-locked, it means that the machine fingerprint is stored along with the activation details.",
      "x-displayName": "Activations"
    },
    {
      "name": "Analytics",
      "description": "You can gain important insights regarding how your customers are using your products and track key metrics like activations over time, activations by country, activations by OS and much more.\n\n",
      "x-displayName": "Analytics"
    },
    {
      "name": "Authentication",
      "description": "This documentation outlines the multiple ways for obtaining an access token (AT) for authenticating your API requests with Cryptlex. You may obtain an access token by using various authentication methods like Email-Password, SAML SSO, and OIDC2.\n\nFor prolonged sessions on a server-side application, you can use personal access tokens (PAT), which can be managed on the [Admin Portal](https://app.cryptlex.com/api/personal-access-tokens). Here are a few guidelines to follow w[...]",
      "x-displayName": "Authentication"
    },
    {
      "name": "AutomatedEmailEventLogs",
      "description": "Automated email event logs provide a complete history of all the automated emails triggered in last 15 days.",
      "x-displayName": "Automated Email Event Logs"
    },
    {
      "name": "AutomatedEmails",
      "description": "Automated emails can be used to send emails automatically to your customers when events like \"license.created\", \"license.renewed\" etc. occur.",
      "x-displayName": "Automated Emails"
    },
    {
      "name": "BillingAddresses",
      "x-displayName": "Billing Addresses"
    },
    {
      "name": "CreditCards",
      "x-displayName": "Credit Cards"
    },
    {
      "name": "EntitlementSets",
      "description": "Entitlement sets group multiple feature entitlements, allowing you to manage and assign them collectively.",
      "x-displayName": "Entitlement Sets"
    },
    {
      "name": "EventLogs",
      "description": "Every resource which is created, updated or deleted is logged along with the user who did that operation. This provides you a complete audit log of every activity going on in your account.",
      "x-displayName": "Event Logs"
    },
    {
      "name": "FeatureFlags",
      "description": "Feature flags help you create different versions of your product with different features.",
      "x-displayName": "Feature Flags"
    },
    {
      "name": "Features",
      "description": "Features allow you to define specific functionalities of your product that can be granted as entitlements.",
      "x-displayName": "Features"
    },
    {
      "name": "Invoices",
      "x-displayName": "Invoices"
    },
    {
      "name": "Licenses",
      "description": "A license is what you use to license your application. Licenses are grouped under products and inherit all the properties of license policy attached to the product.\n\nYou can override all the properties of the license inherited from a license policy if needed.",
      "x-displayName": "Licenses"
    },
    {
      "name": "LicenseTemplates",
      "description": "A license template acts as a blueprint for the licenses you create for your customers and helps you implement different types of licensing models.\n\nA single license template can be shared across different products and each product must have a default license template.",
      "x-displayName": "License Templates"
    },
    {
      "name": "MaintenancePolicies",
      "description": "A maintenance policy can be used to configure how the end-user can update the software (product). A maintenance policy can be used to allow free updates, minor version updates, major version updates upto a specific duration etc.",
      "x-displayName": "Maintenance Policies"
    },
    {
      "name": "OidcConfigurations",
      "x-displayName": "Oidc Configurations"
    },
    {
      "name": "OrganizationActivations",
      "description": "Organization Activations endpoints allow organization users with the 'organization-admin' role to manage activations within the organization.",
      "x-displayName": "Organization Activations"
    },
    {
      "name": "OrganizationLicenses",
      "description": "Organization Licenses endpoints allow organization users with the 'organization-admin' role to manage licenses within the organization.",
      "x-displayName": "Organization Licenses"
    },
    {
      "name": "Organizations",
      "description": "An organization is a group of Users with the `organization-admin` and `user` role which can be assigned to a License. This allows you to assign a License to a group of Users, and allows you to delegate the management of Users to an `organization-admin`.",
      "x-displayName": "Organizations"
    },
    {
      "name": "OrganizationUserGroups",
      "description": "An Organization User Group represents a group of Users in an Organization. It allows Users in the organization with the `organization-admin` role to manage groups of users that can be assigned to licenses.\n\n",
      "x-displayName": "Organization User Groups"
    },
    {
      "name": "OrganizationUsers",
      "description": "Organization Users endpoints allow organization users with the 'organization-admin' role to manage users within the organization.",
      "x-displayName": "Organization Users"
    },
    {
      "name": "PersonalAccessTokens",
      "description": "Personal access tokens are the preferred way for third party applications and scripts to authenticate with the Cryptlex Web API. \n\nThey function similar to API keys and offer fine grained access control. For example in order to create licenses from a script you can create a personal access token with scope (permission) `license:write`. \n\nYou should always scope the token access to minimum required resources, by adding minimum number of permissions.",
      "x-displayName": "Personal Access Tokens"
    },
    {
      "name": "Plans",
      "x-displayName": "Plans"
    },
    {
      "name": "Products",
      "description": "A product refers to your application which you want to license. You will typically create a single product for all your application versions.",
      "x-displayName": "Products"
    },
    {
      "name": "ProductVersions",
      "description": "Product versions can be used to create different versions of your application with the help of feature flags.\n\nYou will typically create a single product for all your application versions and use product versions for different versions of your application. For example, if you offer two versions of your app PRO and LITE then you can create two product versions.",
      "x-displayName": "Product Versions"
    },
    {
      "name": "Profile",
      "x-displayName": "Profile"
    },
    {
      "name": "ReleaseChannels",
      "description": "A release channel refers to the channel (e.g. stable, beta etc.) for which the release is being created.",
      "x-displayName": "Release Channels"
    },
    {
      "name": "ReleaseFiles",
      "description": "A release file contains the information of the uploaded file including url, checksum, size etc.",
      "x-displayName": "Release Files"
    },
    {
      "name": "ReleasePlatforms",
      "description": "A release platform refers to the OS for which the release is being created.",
      "x-displayName": "Release Platforms"
    },
    {
      "name": "Releases",
      "description": "Release management helps you in protection of your software applications from unlicensed distribution. It allows you to host software applications of any size and type on our servers or your own servers, implement auto updates in your application and much more.",
      "x-displayName": "Releases"
    },
    {
      "name": "ResellerActivations",
      "description": "Reseller Activations endpoints allow reseller users with the 'reseller-admin' role to manage activations within the reseller.",
      "x-displayName": "Reseller Activations"
    },
    {
      "name": "ResellerLicenses",
      "description": "Reseller Licenses endpoints allow reseller users with the 'reseller-admin' role to manage licenses within the reseller.",
      "x-displayName": "Reseller Licenses"
    },
    {
      "name": "ResellerOrganizations",
      "description": "Reseller Organizations endpoints allow reseller users with the 'reseller-admin' role to manage organizations within the reseller.",
      "x-displayName": "Reseller Organizations"
    },
    {
      "name": "Resellers",
      "description": "The Reseller feature empowers you to entrust third parties or partners with the responsibility of distributing and managing licenses and users seamlessly on your behalf.",
      "x-displayName": "Resellers"
    },
    {
      "name": "ResellerUsers",
      "description": "Reseller Users endpoints allow reseller users with the 'reseller-admin' role to manage users within the reseller.",
      "x-displayName": "Reseller Users"
    },
    {
      "name": "Roles",
      "description": "Role management helps you manage authorization, which enables you to specify the resources that users in your application are allowed to access. Role management lets you treat groups of users as a unit by assigning users to roles such as manager, sales, developer, and so on.\n\nRole claims refer to permissions which you assign to a role. Every resource has read and write permission which you can add to a role.",
      "x-displayName": "Roles"
    },
    {
      "name": "SamlConfigurations",
      "x-displayName": "Saml Configurations"
    },
    {
      "name": "Segments",
      "x-displayName": "Segments"
    },
    {
      "name": "SendingDomains",
      "x-displayName": "Sending Domains"
    },
    {
      "name": "Tags",
      "description": "Tags help you to group licenses across or within products. You can search licenses using tags.",
      "x-displayName": "Tags"
    },
    {
      "name": "TrialActivations",
      "description": "A trial activation is said to occur when your customer activates the trial in your application on his/her machine.\n\nBy default all trial activations are node-locked, it means that the machine fingerprint is stored along with the trial activation details.",
      "x-displayName": "Trial Activations"
    },
    {
      "name": "TrialPolicies",
      "description": "A trial policy is similar to a license policy, with the difference that it is applicable for trials only. You can create a trial policy using license policies too, but this offers you a cheap and convenient way of doing so.\n\nA single trial policy can be shared across different products and each product may have a trial policy. Not attaching a trial policy to a product disables trials automatically.",
      "x-displayName": "Trial Policies"
    },
    {
      "name": "Users",
      "description": "A user refers to your customer whom you want to license your product. \n\nCryptlex provides identity management for your customers, which means you can authenticate your customers using email/password, and other features like password reset etc.",
      "x-displayName": "Users"
    },
    {
      "name": "WebhookEventLogs",
      "description": "Webhook event logs provide a complete history of all the webhook events triggered in last 15 days.",
      "x-displayName": "Webhook Event Logs"
    },
    {
      "name": "Webhooks",
      "description": "Using webhooks you can subscribe to events, that happen within your Cryptlex account. When one of those events is triggered, we'll send an HTTP POST payload to the webhook's configured URL.",
      "x-displayName": "Webhooks"
    }
  ],
  "x-tagGroups": [
    {
      "name": "Authentication",
      "tags": [
        "Authentication"
      ]
    },
    {
      "name": "Profile",
      "tags": [
        "Profile"
      ]
    },
    {
      "name": "Products",
      "tags": [
        "Products"
      ]
    },
    {
      "name": "Entitlements",
      "tags": [
        "Features",
        "EntitlementSets"
      ]
    },
    {
      "name": "Licenses",
      "tags": [
        "Licenses",
        "Activations",
        "LicenseTemplates",
        "MaintenancePolicies"
      ]
    },
    {
      "name": "Trials",
      "tags": [
        "TrialActivations",
        "TrialPolicies"
      ]
    },
    {
      "name": "Releases",
      "tags": [
        "Releases",
        "ReleaseFiles",
        "ReleasePlatforms",
        "ReleaseChannels"
      ]
    },
    {
      "name": "Users",
      "tags": [
        "Users",
        "Roles"
      ]
    },
    {
      "name": "Organizations",
      "tags": [
        "Organizations",
        "OrganizationUsers",
        "OrganizationUserGroups",
        "OrganizationLicenses",
        "OrganizationActivations"
      ]
    },
    {
      "name": "Resellers",
      "tags": [
        "Resellers",
        "ResellerUsers",
        "ResellerOrganizations",
        "ResellerLicenses",
        "ResellerActivations"
      ]
    },
    {
      "name": "Analytics",
      "tags": [
        "Analytics"
      ]
    },
    {
      "name": "Webhooks",
      "tags": [
        "Webhooks",
        "WebhookEventLogs"
      ]
    },
    {
      "name": "Automated Emails",
      "tags": [
        "AutomatedEmails",
        "AutomatedEmailEventLogs"
      ]
    },
    {
      "name": "Accounts",
      "tags": [
        "Accounts"
      ]
    },
    {
      "name": "Logs",
      "tags": [
        "EventLogs",
        "ActivationLogs"
      ]
    }
  ]
}