{
  "openapi": "3.0.3",
  "info": {
    "title": "Operations Center - Equipment",
    "description": "This API has all the operations for equipment resource.",
    "version": "2.0",
    "x-jentic-source-url": "https://developer.deere.com/devDoc/apiDetails/equipment"
  },
  "servers": [
    {
      "url": "https://equipmentapi.deere.com/isg"
    }
  ],
  "paths": {
    "/equipment": {
      "get": {
        "tags": [
          "Equipment"
        ],
        "description": "This resource allows the client to view the list of a user's equipment. It can be called with a filter for specific organizations, machine or implement types, but can also be called without a filter to provide a list of all equipment accessible by the user across each organization the user has access to. Equipment will only be returned from organizations the user has access to and are connected to the calling application. If the client requests multiple organizations in t[...]",
        "summary": "Get equipment",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ]
      }
    },
    "/organizations/{organizationId}/equipment": {
      "post": {
        "tags": [
          "Equipment"
        ],
        "description": "This resource allows the client to create a piece of equipment within a user’s organization. <br><br> <b>Getting Started</b><br>The process of contributing equipment to John Deere can be broken down into three primary steps. <ol> <li> Determine the Equipment’s model IDs</li> <li> Create the Equipment</li> <li> Contribute Measurements. Please see the <a  href='/dev-docs/equipment-measurement' target='_blank'>Equipment Measurements (POST) API</a> for more information on upl[...]",
        "summary": "Create equipment",
        "operationId": "createEquipment",
        "security": [
          {
            "OAuth2": [
              "eq2"
            ]
          }
        ],
        "__originalOperationId": "createEquipment"
      }
    },
    "/equipment/{id}": {
      "get": {
        "tags": [
          "Equipment"
        ],
        "description": "This resource allows the client to view the details of one piece of equipment.",
        "summary": "View equipment details by Id",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Equipment"
        ],
        "description": "This resource allows the client to update a piece of equipment within a user’s organization. Clients will only be able to update a piece of equipment that was contributed via the POST /equipment API. John Deere controlled equipment can only be managed via the Equipment application in Operations Center.",
        "summary": "Update equipment",
        "operationId": "putEquipment",
        "security": [
          {
            "OAuth2": [
              "eq2"
            ]
          }
        ],
        "__originalOperationId": "putEquipment"
      },
      "delete": {
        "tags": [
          "Equipment"
        ],
        "description": "This resource allows the client to delete a piece of equipment within a user’s organization. Clients will only be able to delete a piece of equipment that was contributed via the POST /equipment API. John Deere controlled equipment can only be managed via the Equipment application in Operations Center.",
        "summary": "Delete equipment",
        "operationId": "deleteEquipment",
        "security": [
          {
            "OAuth2": [
              "eq2"
            ]
          }
        ],
        "__originalOperationId": "deleteEquipment"
      }
    },
    "/equipmentMakes": {
      "get": {
        "tags": [
          "Equipment Makes"
        ],
        "description": "This resource allows the client to view equipment makes and their associated IDs and names.",
        "summary": "Get equipment makes",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "operationId": "getEquipmentMakes",
        "__originalOperationId": "getEquipmentMakes"
      }
    },
    "/equipmentMakes/{equipmentMakeId}": {
      "get": {
        "tags": [
          "Equipment Makes"
        ],
        "description": "This resource allows the client to view equipment makes by an equipment make ID.",
        "summary": "View equipment by make Id",
        "operationId": "getEquipmentMakesById",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "__originalOperationId": "getEquipmentMakesById"
      }
    },
    "/equipmentMakes/{equipmentMakeId}/equipmentTypes": {
      "get": {
        "tags": [
          "Equipment Types"
        ],
        "deprecated": true,
        "description": "This resource allows the client to view equipment types by providing an equipment make ID.",
        "summary": "Get equipment types by make id",
        "note": " <b> Note: </b> This endpoint is <b style=\"color: red;\"> deprecated </b> and should no longer be used.",
        "operationId": "getEquipmentTypesByMakeId",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "__originalOperationId": "getEquipmentTypesByMakeId"
      }
    },
    "/equipmentTypes": {
      "get": {
        "tags": [
          "Equipment Types"
        ],
        "deprecated": true,
        "description": "This resource allows the client to view equipment types and their associated IDs and names.",
        "note": " <b> Note: </b> This endpoint is <b style=\"color: red;\"> deprecated </b> and should no longer be used.",
        "summary": "Get equipment types",
        "operationId": "getEquipmentTypes",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "__originalOperationId": "getEquipmentTypes"
      }
    },
    "/equipmentModels": {
      "get": {
        "tags": [
          "Equipment Models"
        ],
        "description": "This resource allows the client to view equipment models in our reference database and their associated IDs and names.",
        "summary": "Get equipment models",
        "operationId": "getEquipmentModels",
        "__originalOperationId": "getEquipmentModels"
      }
    },
    "/equipmentISGTypes": {
      "get": {
        "tags": [
          "Equipment ISG Type Resource"
        ],
        "description": "This operation retrieves a list of Equipment ISG Types based on the supplied query parameters.",
        "operationId": "getEquipmentISGTypes",
        "summary": "Get equipment ISG types",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "__originalOperationId": "getEquipmentISGTypes"
      }
    },
    "/equipmentMakes/{equipmentMakeId}/equipmentISGTypes": {
      "get": {
        "tags": [
          "Equipment ISG Type Resource"
        ],
        "description": "This operation retrieves a list of Equipment ISG Types for given makeId. <br/>",
        "operationId": "getEquipmentISGTypesByMakeId",
        "summary": "Get equipment ISG types by make id",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "__originalOperationId": "getEquipmentISGTypesByMakeId"
      }
    },
    "/equipmentMakes/{equipmentMakeId}/equipmentISGTypes/{equipmentISGTypeId}": {
      "get": {
        "tags": [
          "Equipment ISG Type Resource"
        ],
        "description": "This operation retrieves a single Equipment ISG Type for given makeId and isgTypeId.. <br/>",
        "operationId": "getEquipmentISGTypeByMakeIdAndISGTypeId",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "summary": "Get equipment ISG type by make id and ISG type id",
        "__originalOperationId": "getEquipmentISGTypeByMakeIdAndISGTypeId"
      }
    },
    "/equipmentMakes/{equipmentMakeId}/equipmentISGTypes/{equipmentISGTypeId}/equipmentModels": {
      "get": {
        "tags": [
          "Equipment Model Resource"
        ],
        "description": "This operation retrieves a list of Equipment Models based on given makeId and ISGtypeId.",
        "operationId": "getEquipmentModelsByMakeIdAndISGTypeId",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "summary": "Get equipment models by make id and ISG type id",
        "__originalOperationId": "getEquipmentModelsByMakeIdAndISGTypeId"
      }
    },
    "/equipmentMakes/{equipmentMakeId}/equipmentISGTypes/{equipmentISGTypeId}/equipmentModels/{equipmentModelId}": {
      "get": {
        "tags": [
          "Equipment Model Resource"
        ],
        "description": "This operation retrieves a single Equipment Model based on given makeId, isgTypeId and modelId.",
        "operationId": "getEquipmentModelsByMakeIdAndISGTypeIdAndModelId",
        "security": [
          {
            "OAuth2": [
              "eq1"
            ]
          }
        ],
        "summary": "Get equipment model by make id, ISG type id and model id",
        "__originalOperationId": "getEquipmentModelsByMakeIdAndISGTypeIdAndModelId"
      }
    }
  },
  "components": {
  }
}