openapi: 3.1.0
info:
  title: Pet API
  version: 1.0.0
servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
paths:
  /pets:
    get:
      summary: List pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                $ref: 'https://gist.githubusercontent.com/char0n/57cada7bccfdef0e25d6d75dafe53397/raw/f8786facb7e70bdc7357226ed9ac271951e6d9cb/pet-list.yaml'
