{
  "openapi": "3.0.3",
  "info": {
    "title": "Regional API GetNet",
    "contact": {},
    "version": "1.0.4",
    "description": "Welcome to GetNet. This API enables your company to integrate with the GetNet Regional API and leverage top-tier payment solutions. GetNet provides secure and efficient services for processing e-commerce transactions, allowing merchants to accept credit, debit, and bank cards seamlessly in their virtual stores. In addition to payment processing, GetNet offers safe, recurring, anti-fraud, conciliator services and other features designed to support your business with speed and [...]",
    "x-jentic-source-url": "https://docs.globalgetnet.com/en/products/online-payments/regional-api/swagger"
  },
  "servers": [
    {
      "url": "https://api.pre.globalgetnet.com"
    },
    {
      "url": "https://api-sbx.globalgetnet.com"
    },
    {
      "url": "https://api.globalgetnet.com"
    }
  ],
  "paths": {
    "/authentication/oauth2/access_token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Authentication Token",
        "description": "__Authentication__<br><br>All transactions are authenticated using a Bearer token generated through the OAuth 2.0 protocol. To obtain a token, clients must send a request to the authentication endpoint using their `client_id` and `client_secret` (click <a href='https://docs.globalgetnet.com/es/articles/api-keys'>here</a> to see how to generate your credentials). To authenticate this request, you must pass the Base64-encoded string of `client_id:client_secret` in the `Auth[...]",
        "operationId": "authentication"
      }
    },
    "/dpm/payments-gwproxy/v2/payments": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create - Authorize",
        "description": "__Create a Payment Transaction__\\u003cbr>\\u003cbr>\nThe Create Payment endpoint allows merchants to initiate a payment transaction \nusing credit or debit cards, as well as alternative payment methods. This request processes the transaction and returns \na response indicating its status. Moreover, this operation also supports installment payments.\\u003cbr>\\u003cbr>\n\n**Notes:**\\u003cbr>\n- Some transactions may require additional steps, such as **authentication** or[...]",
        "operationId": "payment_2",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Payments"
        ],
        "summary": "Adjustment",
        "description": "__Update a Payment Transaction__\\u003cbr>\\u003cbr>\nThis endpoint allows you to update an existing payment transaction. It’s used to modify specific attributes of a transaction, such as updating metadata, correcting information, or adjusting payment details before processing it. Ensure you review the request parameters to verify which modifications are allowed.\\u003cbr>\\u003cbr>\n\n**Notes:**\\u003cbr>\n- Some updates may require additional validation or approval.\\u0[...]",
        "operationId": "adjustment_2",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/capture": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Capture",
        "description": "__Capture an Authorized Payment__\\u003cbr>\\u003cbr>\nThe Capture endpoint is used to finalize a previously successful authorized payment, ensuring that the transaction amount is deducted from the customer’s account and settled to the merchant. The transaction must be __captured__ within the allowed timeframe, otherwise a new transaction __authorization__ is required.\\u003cbr>\\u003cbr>\n\n**Usage Scenarios:**\\u003cbr>\n- Splitting authorization and capture into separa[...]",
        "operationId": "capture_4",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/qrcode": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "QRCode",
        "description": "__Capture an Authorized Payment__\\u003cbr>\\u003cbr> This endpoint is used to receive payments through QR Code. QR Code payments have an expiration limit of 1 minute and 50 seconds. After this period, a new QR Code must be generated, disregarding the previous one.\\u003cbr> This service is available only for VISA and MasterCard.\\u003cbr>\\u003cbr>",
        "operationId": "createQRCode",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/cancel": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Cancel",
        "description": "__Cancel a Captured Payment__\\u003cbr>\\u003cbr>\nThe Cancel endpoint allows merchants to reverse a previously captured payment, ensuring that the transaction amount is refunded to the customer.\\u003cbr>\\u003cbr>\n\n**Usage Scenarios:**\\u003cbr>\n- Voiding a payment that was captured by mistake.\\u003cbr>\n- Handling order cancellations that require a full refund._\\u003cbr>\\u003cbr>\n\n**Notes:**\\u003cbr>\n- Only **captured** payments can be canceled.\\u003cbr>\n- [...]",
        "operationId": "cancel_7",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/boleto": {
      "post": {
        "summary": "Create an Invoice/Boleto",
        "description": "__Generate Payment with Boleto__\\u003cbr>\\u003cbr>\n\nThe Boleto endpoint allows merchants to generate a bank slip (boleto) for customers to complete payments via banking channels, ATMs, or authorized locations. It offers an alternative payment method for customers without credit or debit cards and enables cash-based transactions with a due date for payment.\\u003cbr>\\u003cbr>\n\n**Notes:**\\u003cbr>\n- The boleto must include an expiration date, after which payment is[...]",
        "tags": [
          "Payments"
        ],
        "operationId": "paymentBoleto_1",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/qrcode/pix": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Create PIX",
        "description": "__Generate Payment with PIX__\\u003cbr>\\u003cbr>\nThis endpoint processes payment data and instantly creates a unique PIX QR Code. \nUpon successful payment by the customer, the merchant will receive a **real-time HTTP notification** for confirmation. For details on handling confirmation, refer to the **\"PIX Notifications\"** section in **Notifications 1.1** of the documentation.\\u003cbr>\\u003cbr>\n\n**Usage Scenarios:** \\u003cbr>\n- Supports instant payments 24/7, i[...]",
        "operationId": "pix",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/security-gwproxy/v2/enrolments-initial": {
      "post": {
        "tags": [
          "Payments"
        ],
        "operationId": "initial",
        "description": "__Initiate 3DS Authentication__\\u003cbr>\\u003cbr>\n\n3D Secure (3DS) is an authentication protocol designed to enhance the security of online transactions by verifying the identity of cardholders before a payment is processed. This endpoint initiates the enrolment flow for 3DS authentication, beginning the authentication process for a payment transaction.\\u003cbr>\\u003cbr>\n\n**Usage Scenarios:**\\u003cbr>\n- Adding an extra layer of security to card payments and redu[...]",
        "summary": "3DS - Init Authentication"
      }
    },
    "/dpm/security-gwproxy/v2/enrolments-continue": {
      "post": {
        "tags": [
          "Payments"
        ],
        "operationId": "enrolmentsContinue",
        "summary": "3DS - Banking Login Authentication Payload",
        "description": "This endpoint generates the necessary payload for the customer to authenticate using their banking login. The response includes the required authentication details, which can be used to proceed with the transaction securely."
      }
    },
    "/dpm/security-gwproxy/v2/validations": {
      "post": {
        "tags": [
          "Payments"
        ],
        "operationId": "validations",
        "summary": "3DS - Validate authentication",
        "description": "This endpoint validates a 3DS authentication by verifying the payer authentication response received from the card issuer. It confirms whether the customer has been successfully authenticated, allowing the transaction to proceed securely."
      }
    },
    "/dpm/hub-payment-info/v1/payments/info/{payment_id}": {
      "get": {
        "summary": "Get Transaction",
        "tags": [
          "Payment Record Management"
        ],
        "operationId": "get-v1-payments",
        "description": "__Retrieve transaction details using a unique transaction ID__\\u003cbr>\\u003cbr>The Transaction Query endpoint allows you to retrieve details of a specific transaction using its unique identifier. This is useful for verifying transaction statuses, fetching payment details, and tracking processed transactions.",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/hub-payment-info/v1/payments/info/{payment_id}/{idempotency_key}": {
      "get": {
        "summary": "Get by Idempotent Key",
        "description": "__Retrieving Transaction Data Using Idempotency Keys__\\u003cbr>\\u003cbr>This endpoint allows querying transaction components linked to a specific payment using an **idempotency key**. The idempotency mechanism ensures that repeated requests with the same key will always return the same response, preventing the creation of duplicate transactions.\\u003cbr>\\u003cbr>**Notes:**\\u003cbr>_- Using an idempotency key ensures that repeated queries always return the same transa[...]",
        "tags": [
          "Payment Record Management"
        ],
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ],
        "operationId": "get-v1-payment-info-payment_id-component_id"
      }
    },
    "/dpm/payments-gwproxy/v2/payments/combined": {
      "post": {
        "tags": [
          "Combined Payments"
        ],
        "summary": "Authorize",
        "description": "__Splitting a Transaction Across Multiple Cards__\\u003cbr>\\u003cbr>This endpoint allows you to authorize a combined payment using multiple cards. It is typically used when a buyer wishes to split the total amount across two or more payment methods.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Offering flexibility to the customer in payment options.\\u003cbr>- Handling split transactions for marketplaces or platforms._\\u003cbr>\\u003cbr>**Notes:**\\u003cbr>_- **O[...]",
        "operationId": "combined_",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/payments/combined/capture": {
      "post": {
        "tags": [
          "Combined Payments"
        ],
        "summary": "Capture",
        "description": "__Capture Combined Payments__\\u003cbr>\\u003cbr>This endpoint allows you to **capture a previously authorized combined payment**. It is used to finalize a transaction that was initially authorized using more than one card.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_-  Completing a combined payment after order fulfillment.\\u003cbr>- Capturing authorized funds split across multiple cards.\\u003cbr>- Post-authorization capture logic for marketplaces or platforms.._\[...]",
        "operationId": "capture"
      }
    },
    "/dpm/payments-gwproxy/v2/payments/combined/cancel": {
      "post": {
        "tags": [
          "Combined Payments"
        ],
        "summary": "Cancel",
        "description": "__Cancel Combined Payment__\\u003cbr>\\u003cbr>This endpoint allows you to cancel a previously authorized combined payment. It is typically used when the entire payment (made with more than one card) must be voided before capture.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Full void of a combined authorization due to user request or error.\\u003cbr>- Rejection of payment during fraud analysis or validation stage._\\u003cbr>\\u003cbr>**Notes:**\\u003cbr>_- Only au[...]",
        "operationId": "cancel"
      }
    },
    "/dpm/payments-gwproxy/v1/crossborder/quote": {
      "post": {
        "tags": [
          "Crossborder"
        ],
        "summary": "Get CrossBorder Quote",
        "description": "Retrieve a cross border quote.",
        "operationId": "getCrossborderQuote"
      }
    },
    "/dpm/payments-gwproxy/v2/crossborder/validate-customer": {
      "post": {
        "summary": "Validate customer",
        "tags": [
          "Crossborder"
        ],
        "description": "Submits a new customer for documentation validation. If the document_number has already been submitted, the endpoint will retrieve the customer record with its updated status. When the customer analysis is complete, we will send a webhook with the same response format as the '200' case to a URL registered by the seller at the time of enrollment.",
        "operationId": "validate_fx"
      }
    },
    "/dpm/payments-gwproxy/v2/payments/quotes": {
      "post": {
        "tags": [
          "Installments"
        ],
        "summary": "Get Installments",
        "description": "__Request Installment Quotes__\\u003cbr>\\u003cbr>This endpoint allows you to retrieve a list of available installment quotes for a customer’s payment card. Each quote includes final interest and tax rates, which can be used if the merchant has no pre-negotiated rates with the issuer.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Displaying installment options to users during checkout.\\u003cbr>- Calculating total payment amounts with interest included.\\u003cbr>- P[...]",
        "operationId": "getCuotesApi"
      }
    },
    "/dpm/cofre-gw-proxy/v1/tokens/card": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Generate Token",
        "description": "__Generate Card Token__\\u003cbr>\\u003cbr>This endpoint enables the secure tokenization of card data, a required step to carry out transactions without exposing sensitive card details. Tokenization replaces the actual card number with a token, ensuring PCI compliance and transaction security.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Generating a token for secure storage and future payments.\\u003cbr>- Preparing a card for one-time or recurring transactions.\\u[...]",
        "operationId": "createToken",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/payments-gwproxy/v2/cards/binlookup/{bin}": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "BIN Lookup",
        "description": "__BIN Lookup__\\u003cbr> \\u003cbr>This endpoint retrieves detailed information about a specific BIN (Bank Identification Number), including brand, country of issue, issuer, and product type. It’s used to identify and classify credit or debit cards before processing.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Identifying the brand or network of a card using its BIN.\\u003cbr>- Determining the issuing country or financial institution.\\u003cbr>- Classifying the c[...]",
        "operationId": "consultaBinUsingGET",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/dpm/cofre-gw-proxy/v1/cards": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "Get Cards By Customer Id",
        "description": "__Get Customer’s Saved Cards__\\u003cbr>\\u003cbr>Returns a list of cards previously stored in the Getnet vault, based on the buyer’s `customer_id`. Useful for displaying saved cards for reuse or management.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_-  Retrieve a user’s stored payment methods.\\u003cbr>- Prefill card info at checkout for returning customers.\\u003cbr>- Display saved cards in account management interfaces._\n\n> Availability\n>\n> To use this endpo[...]",
        "operationId": "getCardList",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Store Card in Vault",
        "description": "__Store Card in Vault__\\u003cbr>\\u003cbr>This endpoint securely stores a consumer’s card information in Getnet’s digital vault for future use. It allows the creation of a reusable card resource based on previously tokenized data, enabling seamless and secure transactions without requiring the card details again.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Tokenizing and saving card data for future payments.\\u003cbr>- Enabling subscriptions or billing cycles wit[...]",
        "operationId": "saveCard",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/cofre-gw-proxy/v1/cards/{card_id}": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "Get Card by Id",
        "description": "__Get Card by ID__\\u003cbr>\\u003cbr>Retrieves detailed information about a specific card previously stored in the Getnet vault, using its unique `card_id`.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Retrieve details of a specific saved card.\\u003cbr>- Validate if a stored card is still active.\\u003cbr>- Display or process a specific saved card in the checkout flow._",
        "operationId": "getCard",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Cards"
        ],
        "summary": "Delete Card by Id",
        "description": "__Delete Card by ID__\\u003cbr>\\u003cbr>Deletes a specific card previously stored in the Getnet vault, identified by its `card_id`.\\u003cbr>\\u003cbr>This action removes the card from the buyer’s list of saved payment methods and makes it unavailable for future transactions.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Remove outdated or expired cards.\\u003cbr>- Let users manage (clean up) their saved payment methods.\\u003cbr>- Enhance compliance with data priv[...]",
        "operationId": "removeCard",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/dpm/cofre-gw-proxy/v1/cards/verification": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Card verification",
        "description": "__Verify a Card__\\u003cbr>\\u003cbr>This endpoint allows you to validate a credit card using its tokenized representation. It confirms that the card is valid, active, and not subject to restrictions such as being cancelled, blocked, or expired.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Ensuring the card is valid before storing it in the vault.\\u003cbr>- Verifying a card prior to initiating a payment or subscription.\\u003cbr>- Reducing transaction failures by [...]",
        "operationId": "verificationCard",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-customer/v1/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "Get Customers by Seller Id",
        "description": "__List Customers for a specific Seller__\\u003cbr>\\u003cbr>This endpoint retrieves a paginated list of registered customers associated with a specific seller. It is typically used for customer management, recurrence billing, or administrative queries within the Getnet platform.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Viewing all customers created under a given seller account.\\u003cbr>- Performing administrative tasks such as customer record management or aud[...]",
        "operationId": "getCustomers",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "Create Customer",
        "description": "__Request Installment Quotes__\\u003cbr>\\u003cbr>This endpoint allows you to create a new customer profile within the Getnet platform. It is primarily used for recurrence scenarios, enabling the association of customer data with future payments such as subscriptions, recurring charges, or tokenized transactions.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Associating customer profiles with saved cards or tokenized payments.\\u003cbr>- Enabling customer-specific m[...]",
        "operationId": "postCustomers",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-customer/v1/customers/{customer_id}": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "Get Customer by Id",
        "description": "__Get Customer by Id__\\u003cbr>\\u003cbr>This endpoint retrieves detailed information of a specific customer based on their unique `customer_id`. It is used to fetch full customer records for validation, recurrence processing, or support tasks.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Fetching a customer’s profile for review or display in a dashboard.\\u003cbr>- Validating customer details before processing a new recurring transaction.\\u003cbr>- Verifying sto[...]",
        "operationId": "getCustomersById",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-plan/v1/plans": {
      "get": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Get Plans by Seller Id",
        "description": "__List Recurrence Plans for a specific Seller__\\u003cbr>\\u003cbr>This endpoint allows you to retrieve a paginated list of recurrence plans previously registered on the Getnet platform. It helps manage existing subscription or recurring payment configurations tied to a specific seller.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Displaying available plans for customer enrollment.\\u003cbr>- Reviewing existing billing plan configurations.\\u003cbr>- Auditing or ma[...]",
        "operationId": "plansGet_1",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Create Recurrence Plan",
        "description": "__Register a Recurrence Plan__\\u003cbr>\\u003cbr>This endpoint allows the creation of a recurrence plan, which defines the structure for future scheduled payments. These plans are commonly used for subscriptions, installments, or recurring services.\\u003cbr>\\u003cbr>**Usage Scenarios:**\\u003cbr>_- Creating monthly or yearly subscription plans for digital services or physical products._\\u003cbr>\\u003cbr>**Notes:**\\u003cbr>_- The field_ `seller_id` _is required and m[...]",
        "operationId": "plansPost_1",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-plan/v1/plans/{plan_id}": {
      "get": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Get Plan by Id",
        "description": "__Get Recurrence Plan by Id__\\u003cbr> \\u003cbr>This endpoint retrieves detailed information about a specific recurrence plan using its unique `plan_id`. It is useful for viewing the configuration of a subscription plan, including billing cycle, payment methods, and amount.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Retrieving full details of a recurrence plan for display or review.\\u003cbr>- Validating a specific plan’s configuration before customer subscrip[...]",
        "operationId": "plansIdGet",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Update Plan",
        "description": "__Update a Plan__\\u003cbr> \\u003cbr>This endpoint allows you to update the attributes of an existing recurrence plan. It is typically used to modify plan metadata such as the name, description, or floating installment data without altering its identity or subscription history.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Correcting or improving plan presentation on user-facing interfaces.\\u003cbr>- Adjusting installment options (e.g. adding or modifying floatin[...]",
        "operationId": "plansIdPut",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-plan/v1/plans/subscriptions/migration": {
      "post": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Migrate Subscriptions",
        "description": "__Migrate Subscriptions to Another Plan__\\u003cbr> \\u003cbr>This endpoint allows you to migrate one or more subscriptions from an existing recurrence plan (from) to a new target plan (to). This is useful when updating the terms or pricing of an active subscription without interrupting service to the customer.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Moving existing customers from a legacy plan to a newly structured or updated plan.\\u003cbr>- Updating subscr[...]",
        "operationId": "plansSubscriptionsMigration",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-plan/v1/plans/{plan_id}/status/{status}": {
      "patch": {
        "tags": [
          "Recurrence Plans"
        ],
        "summary": "Update Plan status",
        "operationId": "plansUpdateStatus",
        "description": "__Update Plan status__\\u003cbr> \\u003cbr>This endpoint allows you to update the status of an existing recurrence plan. You can use it to **activate** or **deactivate** (inactive) a plan depending on your business needs. It is commonly used for enabling or pausing plans without deleting them.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Activating a new plan after initial setup.\\u003cbr>- Temporarily deactivating a plan that is no longer available for new subscr[...]",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/webhooks/v1/subscriptions": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Subscribe to a webhook event",
        "description": "Subscribe to receive webhooks. Select the event, authentication type and url to subscribe to an event.",
        "operationId": "post-webhook-subscriptions",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ],
        "callbacks": {
          "APPROVED_TRANSACTIONS": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-approved-transactions"
              }
            }
          },
          "REJECTED_TRANSACTIONS": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-rejected-transactions"
              }
            }
          },
          "REFUNDED_TRANSACTIONS": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-refunded-transactions"
              }
            }
          },
          "CANCELLED_TRANSACTIONS": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-cancelled-transactions"
              }
            }
          },
          "CAPTURED_TRANSACTIONS": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-captured-transactions"
              }
            }
          },
          "CARD_UPDATE": {
            "{$request.body#/callback_url}": {
              "post": {
                "operationId": "webhook-card-update"
              }
            }
          }
        }
      }
    },
    "/webhooks/v1/subscriptions/{subscription_id}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Get a list of all subscriptions events",
        "description": "Obtain a list of all events subscribed by a seller",
        "operationId": "get-webhook-subscriptions",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Subscribe to a webhook event",
        "description": "Subscribe to receive webhooks. Select the event, authentication type and url to subscribe to an event.",
        "operationId": "delete-webhook-subscriptions",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ]
      }
    },
    "/webhooks/v1/subscriptions/{subscription_id}/events": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Get a list of all subscriptions events messages based on filters",
        "description": "Send your specific filtes to obtain a list of messages. The limit of messages is 1000. The default pagination is 20 messages per page.",
        "operationId": "get-webhook-subscriptions-events",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ]
      }
    },
    "/webhooks/v1/subscriptions/{subscription_id}/events/{event_id}": {
      "patch": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Re-send a message",
        "description": "Send your specific filtes to obtain a list of messages. The limit of messages is 1000. The default pagination is 20 messages per page.",
        "operationId": "patch-webhook-subscriptions-events",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ]
      }
    },
    "/webhooks/v1/subscriptions-events": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Get a list of all possible events to subscribe.",
        "description": "Get a list of all possible events to subscribe.",
        "operationId": "get-webhook-events",
        "security": [
          {
            "PROD": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "PRE": [
              "digital-platform-webhooks-api:rw"
            ]
          },
          {
            "SBX": [
              "digital-platform-webhooks-api:rw"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Get Subscriptions",
        "description": "__List Subscriptions__\\u003cbr> \\u003cbr>This endpoint retrieves a paginated list of all subscriptions created by the seller, including their current status, customer details, and plan associations.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Monitoring active or scheduled subscriptions tied to specific customers or plans.\\u003cbr>- Building dashboards or reports with current subscription statuses.\\u003cbr>- Auditing or debugging subscription activity based o[...]",
        "operationId": "subscriptionsGet",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Create Subscription",
        "description": "__Register a New Subscription__\\u003cbr> \\u003cbr>based on a predefined plan. It’s used to enroll a customer into a recurring payment schedule.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Starting a new subscription for digital services, memberships, etc.\\u003cbr>- Associating a buyer to a specific plan with automated recurring billing.\\u003cbr>- Setting a custom start date for the subscription to control billing cycles._\\u003cbr> \\u003cbr>**Notes:**\\u003c[...]",
        "operationId": "subscriptionsPost",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Get Subscription by Id",
        "description": "__Get Subscription by Id__\\u003cbr> \\u003cbr>This endpoint retrieves detailed information about a specific subscription using its unique identifier. It returns data about the plan, billing cycle, customer, and current status of the subscription.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Displaying full subscription details in a customer dashboard or admin panel.\\u003cbr>- Verifying the current status of a subscription (e.g., active, scheduled, canceled).\\u0[...]",
        "operationId": "subscriptionGet",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}/cancel": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Cancel Subscription",
        "description": "__Cancel an Existing Subscription__\\u003cbr> \\u003cbr>This endpoint allows you to cancel an existing subscription using its unique identifier. It updates the subscription status to `CANCELED` and optionally logs a reason for audit and tracking purposes.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- When a customer explicitly requests to stop their subscription.\\u003cbr>- As part of automated processes (e.g., failed payments, policy violations).\\u003cbr>- When a[...]",
        "operationId": "subscriptionCancel",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}/charges/projection": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Projection of Charges",
        "description": "__Demonstrates the projection of charges__\\u003cbr> \\u003cbr>This endpoint returns a detailed projection of the upcoming charges for a specific subscription. It’s useful for understanding future billing dates and amounts, based on the subscription’s billing cycle and current configuration.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Displaying upcoming charges to the customer in a client-facing dashboard.\\u003cbr>- Validating recurring charge patterns for subs[...]",
        "operationId": "chargesProjection",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}/confirmPayment": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Confirm Payment for a Subscription",
        "description": "__Confirm Payment for a Subscription__\\u003cbr> \\u003cbr>This endpoint confirms the payment of a specific charge associated with a subscription. It’s typically used to confirm payments manually in cases where the payment has been completed outside the regular processing flow and needs to be acknowledged within the system.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Marking a charge as paid after receiving manual or offline confirmation (e.g., bank transfer).\\u[...]",
        "operationId": "confirmChargePayment",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}/paymentDate": {
      "patch": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Update Payment Date",
        "description": "__Update Subscription Payment Date__\\u003cbr> \\u003cbr>This endpoint allows merchants to update the recurring payment date of an active subscription. It modifies the day of the month on which future charges will be generated.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Adjusting the charge schedule based on customer preferences.\\u003cbr>- Aligning the subscription billing date with payroll or other payment cycles.\\u003cbr>- Correcting an initial setup error r[...]",
        "operationId": "paymentDatePatch",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscription_id}/paymentType/credit/card": {
      "patch": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Update Payment Data",
        "description": "__Update Subscription Payment Data__\\u003cbr> \\u003cbr>This endpoint allows merchants to update the payment method of an existing subscription, specifically switching to a new or updated credit card.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Updating the credit card for an active subscription.\\u003cbr>- Replacing an expired or invalid card.\\u003cbr>- Switching to a different card brand or issuer for billing._\\u003cbr> \\u003cbr>**Notes:**\\u003cbr>_- The n[...]",
        "operationId": "patchPaymentData",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscriptionId}/floating": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Get Changes of Subscription Installments",
        "description": "__Get Changes of Subscription Installments__\\u003cbr> \\u003cbr>This endpoint retrieves all date and/or value changes made to a specific recurrence subscription’s billing schedule. It allows you to track adjustments to installment amounts or billing dates.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Auditing changes to subscription billing dates or amounts.\\u003cbr>- Validating scheduled changes prior to executing a billing cycle.\\u003cbr>- Troubleshooting sub[...]",
        "operationId": "floatingDataGet",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Set Changes of Subscription Installments",
        "description": "__Set Changes of Subscription Installments__\\u003cbr> \\u003cbr>On this endpoint you can create a new date and/or value change for one or more charges that are scheduled for the subscription. To use this endpoint, the establishment must be enabled for this specific product. For more details see the Date change rules.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Adjusting the charge amount for a specific installment due to discounts or corrections.\\u003cbr>- Chan[...]",
        "operationId": "subscriptionFloatingDataPost",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Delete Changes of Subscription Installments",
        "description": "__Delete Changes of Subscription Installments__\\u003cbr> \\u003cbr>This endpoint deletes all floating data (installment-specific changes) associated with a given subscription. This effectively restores the default installment schedule and values as defined by the plan.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Reverting customized billing dates or amounts back to the default plan settings.\\u003cbr>- Cleaning up outdated or incorrect floating data entries.\\u0[...]",
        "operationId": "floatingDataDeleteAll",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Update Changes of Subscription Installments",
        "description": "__Update Changes of Subscription Installments__\\u003cbr> \\u003cbr>This endpoint updates or creates a floating data entry for a specific subscription. Floating data allows the customization of installment values on specific days of the month, overriding the default schedule and values set by the subscription plan.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Modifying a previously created floating installment value.\\u003cbr>- Adjusting billing behavior to reflec[...]",
        "operationId": "subscriptionFloatingDataPatch",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscriptionId}/floating/installment/{installment}": {
      "put": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Update fluctuation of Subscription Installment",
        "description": "__Updates date and value fluctuation in the subscription for a specific installment__\\u003cbr> \\u003cbr>This endpoint updates a specific installment within a subscription’s floating data, allowing for precise adjustment of both the amount and billing date for that installment. It provides finer control over payment customization beyond regular monthly rules.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Modifying the amount and billing date of a specific installm[...]",
        "operationId": "subscriptionFloatingDataPut",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Delete fluctuation of Subscriptions Installment",
        "description": "__Delete date and value fluctuation in the subscription for a specific installment__\\u003cbr> \\u003cbr>This endpoint deletes a specific floating installment entry from a subscription. It is useful when only one installment within the floating configuration needs to be removed, rather than clearing the entire floating setup.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Removing a single incorrect or outdated floating installment configuration.\\u003cbr>- Revertin[...]",
        "operationId": "floatingDataDelete",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/be-subscription/v1/subscriptions/{subscriptionId}/plans/migration": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Migrate Subscription Plan",
        "description": "__Migrate Subscription Plan__\\u003cbr> \\u003cbr>This endpoint enables the migration of a subscription from one plan to another. It allows merchants to update the terms of an existing subscription by assigning a different predefined plan to it.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Migrating legacy subscriptions to new or updated plans.\\u003cbr>- Adjusting a subscription’s features or pricing structure without requiring cancellation and recreation._",
        "operationId": "migrateSubscriptionPlan",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    },
    "/rpy/adapter-charge/v1/charges": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "summary": "Get All Charges",
        "description": "__List All Charges__\\u003cbr> \\u003cbr>This endpoint retrieves a list of all registered charges in the system. You can apply various filters to narrow down the results, such as filtering by subscription, customer, charge status, and dates.\\u003cbr> \\u003cbr>**Usage Scenarios:**\\u003cbr>_- Viewing all charges within a certain time period.\\u003cbr>- Filtering charges by subscription, customer, or plan.\\u003cbr>- Monitoring charge statuses (e.g., pending, paid, failed[...]",
        "operationId": "getAllCharges",
        "security": [
          {
            "PROD": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "PRE": [
              "digital-platform:gateway-api"
            ]
          },
          {
            "SBX": [
              "digital-platform:gateway-api"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "PROD": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.globalgetnet.com/authentication/oauth2/access_token",
            "scopes": {
              "digital-platform:gateway-api": "Read and write access",
              "digital-platform-webhooks-api:rw": "Creates, updates, or deletes resources using the API",
              "digital-platform-webhooks-api:r": "Retrieves resource details"
            }
          }
        }
      },
      "PRE": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.pre.globalgetnet.com/authentication/oauth2/access_token",
            "scopes": {
              "digital-platform:gateway-api": "Read and write access",
              "digital-platform-webhooks-api:rw": "Creates, updates, or deletes resources using the API",
              "digital-platform-webhooks-api:r": "Retrieves resource details"
            }
          }
        }
      },
      "SBX": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api-sbx.globalgetnet.com/authentication/oauth2/access_token",
            "scopes": {
              "digital-platform:gateway-api": "Read and write access",
              "digital-platform-webhooks-api:rw": "Creates, updates, or deletes resources using the API",
              "digital-platform-webhooks-api:r": "Retrieves resource details"
            }
          }
        }
      },
      "basicAuth": {
        "type": "http",
        "scheme": "basic",
        "description": "Basic Authentication using client_id and client_secret (Base64 encoded)."
      }
    }
  }
}